import {
  faBell,
  faChartLine,
  faClipboardList,
  faCogs,
  faEnvelope,
  faFileInvoiceDollar,
  faFileLines,
  faLifeRing,
  faListAlt,
  faNewspaper,
  faPalette,
  faServer,
  faShoppingCart,
  faSitemap,
  faTachometerAlt,
  faTicketAlt,
  faTrafficLight,
  faTriangleExclamation,
  faUserShield,
  faUsers,
  faWrench,
} from '@fortawesome/free-solid-svg-icons';
import type { AdminNavCounts, AdminNavItem } from './types';

export function buildAdminNavItems(counts: AdminNavCounts): AdminNavItem[] {
  return [
    {
      href: '/admin',
      label: 'Dashboard',
      icon: faTachometerAlt,
    },
    {
      href: '/admin/users',
      label: 'Users',
      badge: String(counts.userCount),
      icon: faUsers,
      section: 'users',
    },
    {
      href: '/admin/organizations',
      label: 'Organizations',
      icon: faSitemap,
      section: 'organizations',
    },
    {
      href: '/admin/transactions',
      label: 'Transactions',
      badge: String(counts.paymentCount),
      icon: faFileInvoiceDollar,
      section: 'transactions',
    },
    {
      href: '/admin/subscriptions',
      label: 'Subscriptions',
      badge: counts.subscriptionsCount > 0 ? String(counts.subscriptionsCount) : undefined,
      icon: faClipboardList,
      section: 'subscriptions',
    },
    {
      href: '/admin/purchases',
      label: 'One-Time Sales',
      badge: counts.purchasesCount > 0 ? String(counts.purchasesCount) : undefined,
      icon: faShoppingCart,
      section: 'purchases',
    },
    {
      href: '/admin/coupons',
      label: 'Coupons',
      badge: counts.couponCount > 0 ? String(counts.couponCount) : undefined,
      icon: faTicketAlt,
      adminOnly: true,
    },
    {
      href: '/admin/pages',
      label: 'Pages',
      icon: faFileLines,
      adminOnly: true,
    },
    {
      href: '/admin/blog',
      label: 'Blog',
      icon: faNewspaper,
      adminOnly: true,
    },
    {
      href: '/admin/moderation',
      label: 'Moderation',
      badge: counts.moderatorLogCount > 0 ? String(Math.min(counts.moderatorLogCount, 99)) : undefined,
      icon: faUserShield,
      adminOnly: true,
    },
    {
      href: '/admin/support',
      label: 'Support',
      badge: counts.ticketCount > 0 ? String(counts.ticketCount) : undefined,
      icon: faLifeRing,
      section: 'support',
    },
    {
      href: '/admin/notifications',
      label: 'Notifications',
      badge: counts.unreadNotifications > 0 ? String(counts.unreadNotifications) : undefined,
      icon: faBell,
      section: 'notifications',
    },
    {
      href: '/admin/emails',
      label: 'Email Templates',
      icon: faEnvelope,
      adminOnly: true,
    },
    {
      href: '/admin/analytics',
      label: 'Analytics',
      icon: faChartLine,
      section: 'analytics',
    },
    {
      href: '/admin/traffic',
      label: 'Traffic',
      icon: faTrafficLight,
      section: 'traffic',
    },
    {
      href: '/admin/plans',
      label: 'Plans',
      icon: faListAlt,
      adminOnly: true,
    },
    {
      href: '/admin/theme',
      label: 'Theme',
      icon: faPalette,
      adminOnly: true,
    },
    {
      href: '/admin/settings',
      label: 'Settings',
      icon: faCogs,
      adminOnly: true,
    },
    {
      href: '/admin/logs',
      label: 'Logs',
      badge: counts.logCount > 0 ? String(counts.logCount) : undefined,
      icon: faTriangleExclamation,
      adminOnly: true,
    },
    {
      href: '/admin/system',
      label: 'System Info',
      icon: faServer,
      adminOnly: true,
    },
    {
      href: '/admin/maintenance',
      label: 'Maintenance',
      icon: faWrench,
      adminOnly: true,
    },
  ];
}