// Central feature registry & gating logic

export enum FeatureId {
  OFFSET_SETTINGS = 'OFFSET_SETTINGS',
  FOV_ADJUST = 'FOV_ADJUST',
  DEPTH_CONTROL = 'DEPTH_CONTROL',
  PREFER_3D_TOGGLE = 'PREFER_3D_TOGGLE',
  IMAGE_DIMENSIONS = 'IMAGE_DIMENSIONS',
  SIDE_FACE_BRIGHTNESS = 'SIDE_FACE_BRIGHTNESS',
  CANVAS_BORDER_RADIUS = 'CANVAS_BORDER_RADIUS',
  CUSTOM_COLOR = 'CUSTOM_COLOR',
  CUSTOM_GRADIENT = 'CUSTOM_GRADIENT',
  GLOW_COLOR = 'GLOW_COLOR',
  HIGH_QUALITY_EDGES = 'HIGH_QUALITY_EDGES',
  EXPORT_SCALE_15 = 'EXPORT_SCALE_15',
  EXPORT_SCALE_20 = 'EXPORT_SCALE_20',
  EXPORT_SCALE_30 = 'EXPORT_SCALE_30',
  EXPORT_SCALE_40 = 'EXPORT_SCALE_40',
  WATERMARK_REMOVAL = 'WATERMARK_REMOVAL',
  SUPPORT_PRIORITY = 'SUPPORT_PRIORITY',
  USAGE_LIMIT_ELEVATED = 'USAGE_LIMIT_ELEVATED',
}

export const PRO_FEATURES: FeatureId[] = [
  FeatureId.OFFSET_SETTINGS,
  FeatureId.FOV_ADJUST,
  FeatureId.DEPTH_CONTROL,
  FeatureId.PREFER_3D_TOGGLE,
  FeatureId.IMAGE_DIMENSIONS,
  FeatureId.SIDE_FACE_BRIGHTNESS,
  FeatureId.CANVAS_BORDER_RADIUS,
  FeatureId.CUSTOM_COLOR,
  FeatureId.CUSTOM_GRADIENT,
  FeatureId.GLOW_COLOR,
  FeatureId.HIGH_QUALITY_EDGES,
  FeatureId.EXPORT_SCALE_15,
  FeatureId.EXPORT_SCALE_20,
  FeatureId.EXPORT_SCALE_30,
  FeatureId.EXPORT_SCALE_40,
  FeatureId.WATERMARK_REMOVAL,
  FeatureId.SUPPORT_PRIORITY,
  FeatureId.USAGE_LIMIT_ELEVATED,
];

export function isProFeature(feature: FeatureId) {
  return PRO_FEATURES.includes(feature);
}
