// Client-side theme palette types/defaults used by the admin theme editor.

export type ColorHexKey =
  | 'bgPrimary'
  | 'bgSecondary'
  | 'panelBg'
  | 'bgTertiary'
  | 'bgQuaternary'
  | 'textPrimary'
  | 'textSecondary'
  | 'textTertiary'
  | 'borderPrimary'
  | 'borderSecondary'
  | 'accentPrimary'
  | 'accentHover'
  | 'headerBg'
  | 'headerText'
  | 'headerBorder'
  | 'stickyHeaderBg'
  | 'stickyHeaderText'
  | 'stickyHeaderBorder'
  | 'sidebarBg'
  | 'sidebarBorder'
  | 'headerShadow'
  | 'panelShadow'
  | 'cardShadow'
  | 'tabsShadow'
  | 'sidebarShadow'
  // Sticky header shadow is configured in Layout tab (not in the Colors tab).
  | 'pageGradientFrom'
  | 'pageGradientVia'
  | 'pageGradientTo'
  | 'cardGradientFrom'
  | 'cardGradientVia'
  | 'cardGradientTo'
  | 'tabsGradientFrom'
  | 'tabsGradientVia'
  | 'tabsGradientTo'
  | 'pageGlow';

export type OpacityKey =
  | 'headerOpacity'
  | 'sidebarOpacity'
  | 'glowOpacity'
  | 'headerBorderOpacity'
  | 'stickyHeaderBorderOpacity';

export type ThemeFontFamily =
  | 'system'
  | 'material'
  | 'fluent'
  | 'apple'
  | 'carbon'
  | 'polaris'
  | 'ant'
  | 'spectrum'
  | 'geist';

export type ColorTokens = {
  bgPrimary: string;
  bgSecondary: string;
  panelBg: string;
  heroBg: string;
  bgTertiary: string;
  bgQuaternary: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  borderPrimary: string;
  borderSecondary: string;
  accentPrimary: string;
  accentHover: string;
  headerBg: string;
  headerOpacity: number;
  headerText: string;
  headerBlur: number;
  headerBorder: string;
  headerBorderOpacity: number;
  headerBorderWidth: number;
  headerMenuFontSize: number;
  headerMenuFontWeight: number;
  fontFamily: ThemeFontFamily;
  stickyHeaderBg: string;
  stickyHeaderOpacity: number;
  stickyHeaderBlur: number;
  stickyHeaderText: string;
  stickyHeaderBorder: string;
  stickyHeaderBorderOpacity: number;
  stickyHeaderBorderWidth: number;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarOpacity: number;
  headerShadow: string;
  headerShadowBlur: number;
  headerShadowSpread: number;
  surfaceRadius: number;
  statCardAccentTop: number;
  statCardAccentLeft: number;
  panelShadow: string;
  panelShadowBlur: number;
  panelShadowSpread: number;
  cardShadow: string;
  cardShadowBlur: number;
  cardShadowSpread: number;
  tabsShadow: string;
  tabsShadowBlur: number;
  tabsShadowSpread: number;
  sidebarShadow: string;
  sidebarShadowBlur: number;
  sidebarShadowSpread: number;
  stickyHeaderShadow: string;
  stickyHeaderShadowBlur: number;
  stickyHeaderShadowSpread: number;
  pageGradientFrom: string;
  pageGradientVia: string;
  pageGradientTo: string;
  heroGradientFrom: string;
  heroGradientVia: string;
  heroGradientTo: string;
  cardGradientFrom: string;
  cardGradientVia: string;
  cardGradientTo: string;
  tabsGradientFrom: string;
  tabsGradientVia: string;
  tabsGradientTo: string;
  pageGlow: string;
  glowOpacity: number;
};

type ElementGradientKeys =
  | 'heroGradientFrom'
  | 'heroGradientVia'
  | 'heroGradientTo'
  | 'cardGradientFrom'
  | 'cardGradientVia'
  | 'cardGradientTo'
  | 'tabsGradientFrom'
  | 'tabsGradientVia'
  | 'tabsGradientTo';

type OptionalPresetKeys =
  | ElementGradientKeys
  | 'headerText'
  | 'headerBlur'
  | 'headerBorder'
  | 'headerBorderOpacity'
  | 'headerBorderWidth'
  | 'stickyHeaderBg'
  | 'stickyHeaderOpacity'
  | 'stickyHeaderBlur'
  | 'stickyHeaderText'
  | 'stickyHeaderBorder'
  | 'stickyHeaderBorderOpacity'
  | 'stickyHeaderBorderWidth';

// Optional across presets so existing built-ins don't need updates.
type OptionalEffectKeys =
  | 'sidebarBorder'
  | 'headerShadow'
  | 'headerShadowBlur'
  | 'headerShadowSpread'
  | 'surfaceRadius'
  | 'statCardAccentTop'
  | 'statCardAccentLeft'
  | 'panelShadow'
  | 'panelShadowBlur'
  | 'panelShadowSpread'
  | 'cardShadow'
  | 'cardShadowBlur'
  | 'cardShadowSpread'
  | 'tabsShadow'
  | 'tabsShadowBlur'
  | 'tabsShadowSpread'
  | 'sidebarShadow'
  | 'sidebarShadowBlur'
  | 'sidebarShadowSpread'
  | 'stickyHeaderShadow'
  | 'stickyHeaderShadowBlur'
  | 'stickyHeaderShadowSpread'
  | 'headerMenuFontSize'
  | 'headerMenuFontWeight'
  | 'fontFamily';

const sanitizeThemeFontFamily = (value: unknown, fallback: ThemeFontFamily): ThemeFontFamily => {
  return (
    value === 'material' ||
    value === 'fluent' ||
    value === 'apple' ||
    value === 'system' ||
    value === 'carbon' ||
    value === 'polaris' ||
    value === 'ant' ||
    value === 'spectrum' ||
    value === 'geist'
  )
    ? value
    : fallback;
};

export type PartialColorTokens = Omit<ColorTokens, OptionalPresetKeys | OptionalEffectKeys> &
  Partial<Pick<ColorTokens, OptionalPresetKeys | OptionalEffectKeys>>;

export const fillElementGradients = (t: PartialColorTokens): ColorTokens => {
  const clampInt = (n: unknown, min: number, max: number, fallback: number) => {
    const num = typeof n === 'number' ? n : typeof n === 'string' ? Number(n) : NaN;
    if (!Number.isFinite(num)) return fallback;
    return Math.max(min, Math.min(max, Math.round(num)));
  };

  return {
    ...(t as Omit<ColorTokens, ElementGradientKeys>),
    headerText: t.headerText ?? t.textPrimary,
    headerBlur: typeof t.headerBlur === 'number' ? t.headerBlur : 12,
    headerBorder: t.headerBorder ?? t.borderPrimary,
    headerBorderOpacity: typeof t.headerBorderOpacity === 'number' ? t.headerBorderOpacity : 1,
    headerBorderWidth: typeof t.headerBorderWidth === 'number' ? t.headerBorderWidth : 1,
    headerMenuFontSize: clampInt(t.headerMenuFontSize, 10, 20, 14),
    headerMenuFontWeight: clampInt(t.headerMenuFontWeight, 300, 800, 400),
    fontFamily: sanitizeThemeFontFamily(t.fontFamily, 'system'),
    stickyHeaderBg: t.stickyHeaderBg ?? t.headerBg,
    stickyHeaderOpacity: typeof t.stickyHeaderOpacity === 'number' ? t.stickyHeaderOpacity : 1,
    stickyHeaderBlur: typeof t.stickyHeaderBlur === 'number' ? t.stickyHeaderBlur : 14,
    stickyHeaderText: t.stickyHeaderText ?? t.headerText ?? t.textPrimary,
    stickyHeaderBorder: t.stickyHeaderBorder ?? t.headerBorder ?? t.borderPrimary,
    stickyHeaderBorderOpacity: typeof t.stickyHeaderBorderOpacity === 'number' ? t.stickyHeaderBorderOpacity : 1,
    stickyHeaderBorderWidth:
      typeof t.stickyHeaderBorderWidth === 'number'
        ? t.stickyHeaderBorderWidth
        : typeof t.headerBorderWidth === 'number'
          ? t.headerBorderWidth
          : 1,
    sidebarBorder: t.sidebarBorder ?? t.borderPrimary,
    headerShadow: t.headerShadow ?? '#00000014',
    headerShadowBlur: clampInt(t.headerShadowBlur, 0, 80, 30),
    headerShadowSpread: clampInt(t.headerShadowSpread, -80, 80, -22),
    surfaceRadius: clampInt(t.surfaceRadius, 0, 32, 16),
    statCardAccentTop: clampInt(t.statCardAccentTop, 0, 8, 0),
    statCardAccentLeft: clampInt(t.statCardAccentLeft, 0, 8, 0),
    panelShadow: t.panelShadow ?? t.cardShadow ?? '#00000012',
    panelShadowBlur: clampInt(t.panelShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    panelShadowSpread: clampInt(t.panelShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    cardShadow: t.cardShadow ?? '#00000014',
    cardShadowBlur: clampInt(t.cardShadowBlur, 0, 80, 24),
    cardShadowSpread: clampInt(t.cardShadowSpread, -80, 80, -18),
    tabsShadow: t.tabsShadow ?? t.cardShadow ?? '#00000010',
    tabsShadowBlur: clampInt(t.tabsShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    tabsShadowSpread: clampInt(t.tabsShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    sidebarShadow: t.sidebarShadow ?? t.panelShadow ?? t.headerShadow ?? '#00000010',
    sidebarShadowBlur: clampInt(
      t.sidebarShadowBlur,
      0,
      80,
      clampInt(t.panelShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    ),
    sidebarShadowSpread: clampInt(
      t.sidebarShadowSpread,
      -80,
      80,
      clampInt(t.panelShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    ),
    stickyHeaderShadow: t.stickyHeaderShadow ?? t.headerShadow ?? '#00000014',
    stickyHeaderShadowBlur: clampInt(t.stickyHeaderShadowBlur, 0, 80, clampInt(t.headerShadowBlur, 0, 80, 30)),
    stickyHeaderShadowSpread: clampInt(
      t.stickyHeaderShadowSpread,
      -80,
      80,
      clampInt(t.headerShadowSpread, -80, 80, -22),
    ),
    heroGradientFrom: t.heroGradientFrom ?? t.pageGradientFrom,
    heroGradientVia: t.heroGradientVia ?? t.pageGradientVia,
    heroGradientTo: t.heroGradientTo ?? t.pageGradientTo,
    cardGradientFrom: t.cardGradientFrom ?? t.pageGradientFrom,
    cardGradientVia: t.cardGradientVia ?? t.pageGradientVia,
    cardGradientTo: t.cardGradientTo ?? t.pageGradientTo,
    tabsGradientFrom: t.tabsGradientFrom ?? t.pageGradientFrom,
    tabsGradientVia: t.tabsGradientVia ?? t.pageGradientVia,
    tabsGradientTo: t.tabsGradientTo ?? t.pageGradientTo,
  };
};

export type ThemeColorPalette = { light: ColorTokens; dark: ColorTokens };

export type ThemeColorPreset = { name: string; light: ColorTokens; dark: ColorTokens };

export const DEFAULT_LIGHT_COLORS: ColorTokens = {
  bgPrimary: '#ffffff',
  bgSecondary: '#f9fafb',
  panelBg: '#f9fafb',
  heroBg: '#f9fafb',
  bgTertiary: '#f3f4f6',
  bgQuaternary: '#e5e7eb',
  textPrimary: '#111827',
  textSecondary: '#4b5563',
  textTertiary: '#6b7280',
  borderPrimary: '#d1d5db',
  borderSecondary: '#9ca3af',
  accentPrimary: '#3b82f6',
  accentHover: '#2563eb',
  headerBg: '#ffffff37',
  headerOpacity: 1,
  headerText: '#111827',
  headerBlur: 20,
  headerBorder: '#d1d5db4c',
  headerBorderOpacity: 1,
  headerBorderWidth: 1,
  headerMenuFontSize: 14,
  headerMenuFontWeight: 600,
  fontFamily: 'system',
  stickyHeaderBg: '#ffffff3e',
  stickyHeaderOpacity: 1,
  stickyHeaderBlur: 15,
  stickyHeaderText: '#111827',
  stickyHeaderBorder: '#cccfd420',
  stickyHeaderBorderOpacity: 1,
  stickyHeaderBorderWidth: 1,
  sidebarBg: '#ffffff80',
  sidebarBorder: '#ececec6c',
  sidebarOpacity: 1,
  headerShadow: '#00000062',
  headerShadowBlur: 30,
  headerShadowSpread: -27,
  surfaceRadius: 16,
  statCardAccentTop: 0,
  statCardAccentLeft: 0,
  panelShadow: '#0f172a10',
  panelShadowBlur: 18,
  panelShadowSpread: -18,
  cardShadow: '#0f172a12',
  cardShadowBlur: 24,
  cardShadowSpread: -18,
  tabsShadow: '#0f172a10',
  tabsShadowBlur: 20,
  tabsShadowSpread: -16,
  sidebarShadow: '#0f172a14',
  sidebarShadowBlur: 22,
  sidebarShadowSpread: -20,
  stickyHeaderShadow: '#9e9c9cef',
  stickyHeaderShadowBlur: 30,
  stickyHeaderShadowSpread: -23,
  pageGradientFrom: '#ffffff',
  pageGradientVia: '#d8ecfa',
  pageGradientTo: '#ffffff',
  heroGradientFrom: '#f0f9ff00',
  heroGradientVia: '#eef2ff',
  heroGradientTo: '#ffffff',
  cardGradientFrom: '#f0f9ff',
  cardGradientVia: '#eef2ff',
  cardGradientTo: '#ffffff',
  tabsGradientFrom: '#ffffff',
  tabsGradientVia: '#eef2ff',
  tabsGradientTo: '#ffffff',
  pageGlow: '#3b82f673',
  glowOpacity: 1,
};

export const DEFAULT_DARK_COLORS: ColorTokens = {
  bgPrimary: '#0a0a0a',
  bgSecondary: '#171717',
  panelBg: '#171717',
  heroBg: '#171717',
  bgTertiary: '#262626',
  bgQuaternary: '#404040',
  textPrimary: '#f5f5f5',
  textSecondary: '#a3a3a3',
  textTertiary: '#737373',
  borderPrimary: '#4040407f',
  borderSecondary: '#4d4d4dc3',
  accentPrimary: '#3b82f6',
  accentHover: '#2563eb',
  headerBg: '#0a0a0a3e',
  headerOpacity: 1,
  headerText: '#f5f5f5',
  headerBlur: 12,
  headerBorder: '#31313179',
  headerBorderOpacity: 1,
  headerBorderWidth: 1,
  headerMenuFontSize: 14,
  headerMenuFontWeight: 600,
  fontFamily: 'system',
  stickyHeaderBg: '#0a0a0a35',
  stickyHeaderOpacity: 1,
  stickyHeaderBlur: 15,
  stickyHeaderText: '#f5f5f5',
  stickyHeaderBorder: '#40404000',
  stickyHeaderBorderOpacity: 1,
  stickyHeaderBorderWidth: 1,
  sidebarBg: '#1717175d',
  sidebarBorder: '#40404000',
  sidebarOpacity: 1,
  headerShadow: '#8e8e8e61',
  headerShadowBlur: 30,
  headerShadowSpread: -23,
  surfaceRadius: 16,
  statCardAccentTop: 0,
  statCardAccentLeft: 0,
  panelShadow: '#00000040',
  panelShadowBlur: 18,
  panelShadowSpread: -18,
  cardShadow: '#00000052',
  cardShadowBlur: 26,
  cardShadowSpread: -18,
  tabsShadow: '#00000042',
  tabsShadowBlur: 22,
  tabsShadowSpread: -16,
  sidebarShadow: '#0000004f',
  sidebarShadowBlur: 24,
  sidebarShadowSpread: -22,
  stickyHeaderShadow: '#6f6f6f7d',
  stickyHeaderShadowBlur: 30,
  stickyHeaderShadowSpread: -19,
  pageGradientFrom: '#171717',
  pageGradientVia: '#312e81',
  pageGradientTo: '#0a0a0a',
  heroGradientFrom: '#171717',
  heroGradientVia: '#312e81',
  heroGradientTo: '#0a0a0a',
  cardGradientFrom: '#171717',
  cardGradientVia: '#312e81',
  cardGradientTo: '#0a0a0a',
  tabsGradientFrom: '#171717',
  tabsGradientVia: '#312e81',
  tabsGradientTo: '#0a0a0a',
  pageGlow: '#6366f1c7',
  glowOpacity: 1,
};

export const COLOR_LABELS: Record<ColorHexKey, string> = {
  bgPrimary: 'Base background',
  bgSecondary: 'Stat / info cards',
  panelBg: 'Panels',
  bgTertiary: 'Input fields',
  bgQuaternary: 'Hover fills',
  textPrimary: 'Primary text',
  textSecondary: 'Secondary text',
  textTertiary: 'Placeholder text',
  borderPrimary: 'Primary border',
  borderSecondary: 'Secondary border',
  accentPrimary: 'Primary accent',
  accentHover: 'Accent hover',
  headerBg: 'Header background',
  headerText: 'Header text',
  headerBorder: 'Header border (bottom)',
  stickyHeaderBg: 'Sticky header background',
  stickyHeaderText: 'Sticky header text',
  stickyHeaderBorder: 'Sticky header border (bottom)',
  sidebarBg: 'Sidebar background',
  sidebarBorder: 'Sidebar border',
  headerShadow: 'Header drop shadow',
  panelShadow: 'Panel shadow',
  cardShadow: 'Card shadow',
  tabsShadow: 'Tab strip shadow',
  sidebarShadow: 'Sidebar shadow',
  pageGradientFrom: 'Page background (from)',
  pageGradientVia: 'Page background (via)',
  pageGradientTo: 'Page background (to)',
  cardGradientFrom: 'Stat / info gradient (from)',
  cardGradientVia: 'Stat / info gradient (via)',
  cardGradientTo: 'Stat / info gradient (to)',
  tabsGradientFrom: 'Tab strip gradient (from)',
  tabsGradientVia: 'Tab strip gradient (via)',
  tabsGradientTo: 'Tab strip gradient (to)',
  pageGlow: 'Backdrop glow accent',
};

export const COLOR_GROUPS: Array<{ title: string; keys: ColorHexKey[] }> = [
  {
    title: 'General',
    keys: ['borderPrimary', 'borderSecondary', 'accentPrimary', 'accentHover'],
  },
  {
    title: 'Backgrounds',
    keys: ['bgPrimary', 'bgTertiary', 'bgQuaternary', 'pageGradientFrom', 'pageGradientVia', 'pageGradientTo', 'pageGlow'],
  },
  {
    title: 'Surfaces',
    keys: [
      'bgSecondary',
      'panelBg',
      'cardGradientFrom',
      'cardGradientVia',
      'cardGradientTo',
    ],
  },
  { title: 'Text', keys: ['textPrimary', 'textSecondary', 'textTertiary'] },
  { title: 'Header', keys: ['headerBg', 'headerText', 'headerBorder', 'headerShadow'] },
  { title: 'Elevation', keys: ['panelShadow', 'cardShadow', 'tabsShadow', 'sidebarShadow'] },
  { title: 'Layout', keys: ['sidebarBg', 'sidebarBorder'] },
  { title: 'Tab Strip Gradient', keys: ['tabsGradientFrom', 'tabsGradientVia', 'tabsGradientTo'] },
];

export const LIGHT_PRESETS: Array<{ name: string; accent: string; colors: PartialColorTokens }> = [
  {
    name: 'Default',
    accent: DEFAULT_LIGHT_COLORS.accentPrimary,
    colors: DEFAULT_LIGHT_COLORS,
  },
  // ── Gridline ──────────────────────────────────────────────────────────
  // Flat, no glow, no gradients · 0 radius · strong visible borders ·
  // solid opaque white header · left accent 4 px · neutral gray palette
  // with a bright blue accent · structured utility style
  {
    name: 'Gridline',
    accent: '#0f62fe',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#f4f4f4',
      panelBg: '#ffffff',
      heroBg: '#f4f4f4',
      bgTertiary: '#e0e0e0',
      bgQuaternary: '#c6c6c6',
      textPrimary: '#161616',
      textSecondary: '#525252',
      textTertiary: '#6f6f6f',
      borderPrimary: '#e0e0e0',
      borderSecondary: '#8d8d8d',
      accentPrimary: '#0f62fe',
      accentHover: '#0043ce',
      headerBg: '#fffffffa',
      headerOpacity: 1,
      headerText: '#161616',
      headerBlur: 0,
      headerBorder: '#e0e0e0',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 400,
      fontFamily: 'carbon',
      stickyHeaderBg: '#fffffffa',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#161616',
      stickyHeaderBorder: '#e0e0e0',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f4f4f4f5',
      sidebarBorder: '#e0e0e0',
      sidebarOpacity: 1,
      headerShadow: '#00000000',
      headerShadowBlur: 0,
      headerShadowSpread: 0,
      surfaceRadius: 0,
      statCardAccentTop: 0,
      statCardAccentLeft: 4,
      panelShadow: '#00000000',
      panelShadowBlur: 0,
      panelShadowSpread: 0,
      cardShadow: '#00000000',
      cardShadowBlur: 0,
      cardShadowSpread: 0,
      tabsShadow: '#00000000',
      tabsShadowBlur: 0,
      tabsShadowSpread: 0,
      sidebarShadow: '#00000000',
      sidebarShadowBlur: 0,
      sidebarShadowSpread: 0,
      stickyHeaderShadow: '#00000000',
      stickyHeaderShadowBlur: 0,
      stickyHeaderShadowSpread: 0,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#ffffff',
      pageGradientTo: '#ffffff',
      heroGradientFrom: '#f4f4f4',
      heroGradientVia: '#f4f4f4',
      heroGradientTo: '#f4f4f4',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#ffffff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#ffffff',
      tabsGradientVia: '#ffffff',
      tabsGradientTo: '#ffffff',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Evergreen ─────────────────────────────────────────────────────────
  // Warm off-white tones · soft card shadows · rounded (8 px) ·
  // solid header · green accent · no glow · top accent 3 px
  {
    name: 'Evergreen',
    accent: '#008060',
    colors: {
      bgPrimary: '#f6f6f7',
      bgSecondary: '#ffffff',
      panelBg: '#ffffff',
      heroBg: '#f1f2f4',
      bgTertiary: '#e4e5e7',
      bgQuaternary: '#c9cccf',
      textPrimary: '#202223',
      textSecondary: '#6d7175',
      textTertiary: '#8c9196',
      borderPrimary: '#c9cccf',
      borderSecondary: '#8c9196',
      accentPrimary: '#008060',
      accentHover: '#006e52',
      headerBg: '#ffffffee',
      headerOpacity: 1,
      headerText: '#202223',
      headerBlur: 0,
      headerBorder: '#e1e3e5',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'polaris',
      stickyHeaderBg: '#fffffff2',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#202223',
      stickyHeaderBorder: '#e1e3e5',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f6f6f7f0',
      sidebarBorder: '#e1e3e5',
      sidebarOpacity: 1,
      headerShadow: '#0000000a',
      headerShadowBlur: 4,
      headerShadowSpread: -4,
      surfaceRadius: 8,
      statCardAccentTop: 2,
      statCardAccentLeft: 0,
      panelShadow: '#1a1a1a0d',
      panelShadowBlur: 6,
      panelShadowSpread: -2,
      cardShadow: '#1a1a1a14',
      cardShadowBlur: 8,
      cardShadowSpread: -2,
      tabsShadow: '#1a1a1a0a',
      tabsShadowBlur: 6,
      tabsShadowSpread: -4,
      sidebarShadow: '#1a1a1a08',
      sidebarShadowBlur: 4,
      sidebarShadowSpread: -4,
      stickyHeaderShadow: '#1a1a1a0a',
      stickyHeaderShadowBlur: 4,
      stickyHeaderShadowSpread: -4,
      pageGradientFrom: '#f6f6f7',
      pageGradientVia: '#f6f6f7',
      pageGradientTo: '#f6f6f7',
      heroGradientFrom: '#f1f2f4',
      heroGradientVia: '#f1f2f4',
      heroGradientTo: '#f1f2f4',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#ffffff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#f6f6f7',
      tabsGradientVia: '#f6f6f7',
      tabsGradientTo: '#f6f6f7',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Keystone ──────────────────────────────────────────────────────────
  // Clean professional · 6 px radius · medium card shadows · blue
  // accent (#1677ff) · solid header with subtle shadow · no glow ·
  // subtle card gradients · top accent 2 px
  {
    name: 'Keystone',
    accent: '#1677ff',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#fafafa',
      panelBg: '#ffffff',
      heroBg: '#f5f5f5',
      bgTertiary: '#f0f0f0',
      bgQuaternary: '#d9d9d9',
      textPrimary: '#000000e0',
      textSecondary: '#00000073',
      textTertiary: '#00000040',
      borderPrimary: '#d9d9d9',
      borderSecondary: '#bfbfbf',
      accentPrimary: '#1677ff',
      accentHover: '#4096ff',
      headerBg: '#fffffffc',
      headerOpacity: 1,
      headerText: '#000000e0',
      headerBlur: 0,
      headerBorder: '#f0f0f0',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'ant',
      stickyHeaderBg: '#fffffffc',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#000000e0',
      stickyHeaderBorder: '#f0f0f0',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#ffffff',
      sidebarBorder: '#f0f0f0',
      sidebarOpacity: 1,
      headerShadow: '#0505050f',
      headerShadowBlur: 8,
      headerShadowSpread: -6,
      surfaceRadius: 6,
      statCardAccentTop: 2,
      statCardAccentLeft: 0,
      panelShadow: '#0000000d',
      panelShadowBlur: 8,
      panelShadowSpread: -4,
      cardShadow: '#00000012',
      cardShadowBlur: 12,
      cardShadowSpread: -4,
      tabsShadow: '#0000000a',
      tabsShadowBlur: 8,
      tabsShadowSpread: -4,
      sidebarShadow: '#00000008',
      sidebarShadowBlur: 6,
      sidebarShadowSpread: -6,
      stickyHeaderShadow: '#0505050f',
      stickyHeaderShadowBlur: 8,
      stickyHeaderShadowSpread: -6,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#ffffff',
      pageGradientTo: '#ffffff',
      heroGradientFrom: '#f5f5f5',
      heroGradientVia: '#fafafa',
      heroGradientTo: '#f5f5f5',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fafafa',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#ffffff',
      tabsGradientVia: '#ffffff',
      tabsGradientTo: '#ffffff',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Prism ─────────────────────────────────────────────────────────────
  // Refined, accessibility-first · 4 px radius · moderate shadows ·
  // header blur (16 px) · blue accent · left accent 3 px · calm
  // professional gradients · no glow
  {
    name: 'Prism',
    accent: '#0d66d0',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#f8f8f8',
      panelBg: '#ffffff',
      heroBg: '#f4f4f4',
      bgTertiary: '#eaeaea',
      bgQuaternary: '#d0d0d0',
      textPrimary: '#2c2c2c',
      textSecondary: '#6e6e6e',
      textTertiary: '#909090',
      borderPrimary: '#d0d0d0',
      borderSecondary: '#b3b3b3',
      accentPrimary: '#0d66d0',
      accentHover: '#095aba',
      headerBg: '#ffffffd0',
      headerOpacity: 1,
      headerText: '#2c2c2c',
      headerBlur: 16,
      headerBorder: '#e1e1e1a0',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'spectrum',
      stickyHeaderBg: '#ffffffd8',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 16,
      stickyHeaderText: '#2c2c2c',
      stickyHeaderBorder: '#e1e1e190',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f8f8f8e0',
      sidebarBorder: '#e1e1e1',
      sidebarOpacity: 1,
      headerShadow: '#00000010',
      headerShadowBlur: 12,
      headerShadowSpread: -10,
      surfaceRadius: 4,
      statCardAccentTop: 0,
      statCardAccentLeft: 3,
      panelShadow: '#00000010',
      panelShadowBlur: 10,
      panelShadowSpread: -6,
      cardShadow: '#00000018',
      cardShadowBlur: 16,
      cardShadowSpread: -6,
      tabsShadow: '#0000000c',
      tabsShadowBlur: 10,
      tabsShadowSpread: -6,
      sidebarShadow: '#0000000a',
      sidebarShadowBlur: 8,
      sidebarShadowSpread: -8,
      stickyHeaderShadow: '#00000012',
      stickyHeaderShadowBlur: 12,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#fafbfc',
      pageGradientTo: '#ffffff',
      heroGradientFrom: '#f4f4f4',
      heroGradientVia: '#f8f8f8',
      heroGradientTo: '#f4f4f4',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fcfcfc',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#ffffff',
      tabsGradientVia: '#fafafa',
      tabsGradientTo: '#ffffff',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Baseline ──────────────────────────────────────────────────────────
  // Clean dev-tool aesthetic · 6 px radius · subtle shadows · blue
  // accent · solid header with visible bottom border · no glow · no
  // accents · neutral cool-gray scale
  {
    name: 'Baseline',
    accent: '#0969da',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#f6f8fa',
      panelBg: '#ffffff',
      heroBg: '#f6f8fa',
      bgTertiary: '#eaeef2',
      bgQuaternary: '#d0d7de',
      textPrimary: '#1f2328',
      textSecondary: '#656d76',
      textTertiary: '#8b949e',
      borderPrimary: '#d0d7de',
      borderSecondary: '#afb8c1',
      accentPrimary: '#0969da',
      accentHover: '#0550ae',
      headerBg: '#f6f8faf0',
      headerOpacity: 1,
      headerText: '#1f2328',
      headerBlur: 0,
      headerBorder: '#d0d7de',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'system',
      stickyHeaderBg: '#f6f8faf5',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#1f2328',
      stickyHeaderBorder: '#d0d7de',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f6f8faf0',
      sidebarBorder: '#d0d7de',
      sidebarOpacity: 1,
      headerShadow: '#0000000a',
      headerShadowBlur: 4,
      headerShadowSpread: -4,
      surfaceRadius: 6,
      statCardAccentTop: 0,
      statCardAccentLeft: 0,
      panelShadow: '#0100000d',
      panelShadowBlur: 6,
      panelShadowSpread: -4,
      cardShadow: '#01000012',
      cardShadowBlur: 8,
      cardShadowSpread: -4,
      tabsShadow: '#0100000a',
      tabsShadowBlur: 6,
      tabsShadowSpread: -4,
      sidebarShadow: '#01000008',
      sidebarShadowBlur: 4,
      sidebarShadowSpread: -4,
      stickyHeaderShadow: '#0100000a',
      stickyHeaderShadowBlur: 4,
      stickyHeaderShadowSpread: -4,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#ffffff',
      pageGradientTo: '#ffffff',
      heroGradientFrom: '#f6f8fa',
      heroGradientVia: '#f6f8fa',
      heroGradientTo: '#f6f8fa',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#ffffff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#ffffff',
      tabsGradientVia: '#ffffff',
      tabsGradientTo: '#ffffff',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Monochrome ────────────────────────────────────────────────────────
  // Apple HIG-inspired · 12 px radius · minimal shadows ·
  // glass header (blur 20) · blue-gray tinted neutrals · no glow ·
  // no stat-card accents · swiss minimalism
  {
    name: 'Monochrome',
    accent: '#1d1d1f',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#f5f5f7',
      panelBg: '#ffffff',
      heroBg: '#f5f5f7',
      bgTertiary: '#f2f2f7',
      bgQuaternary: '#e5e5ea',
      textPrimary: '#1d1d1f',
      textSecondary: '#6e6e73',
      textTertiary: '#86868b',
      borderPrimary: '#d2d2d7',
      borderSecondary: '#c7c7cc',
      accentPrimary: '#1d1d1f',
      accentHover: '#000000',
      headerBg: '#ffffffa0',
      headerOpacity: 1,
      headerText: '#1d1d1f',
      headerBlur: 20,
      headerBorder: '#d2d2d790',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 400,
      fontFamily: 'geist',
      stickyHeaderBg: '#ffffffb0',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 20,
      stickyHeaderText: '#1d1d1f',
      stickyHeaderBorder: '#d2d2d780',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f5f5f790',
      sidebarBorder: '#d2d2d780',
      sidebarOpacity: 1,
      headerShadow: '#0000000a',
      headerShadowBlur: 10,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      statCardAccentLeft: 0,
      panelShadow: '#00000008',
      panelShadowBlur: 8,
      panelShadowSpread: -6,
      cardShadow: '#00000010',
      cardShadowBlur: 12,
      cardShadowSpread: -8,
      tabsShadow: '#00000006',
      tabsShadowBlur: 8,
      tabsShadowSpread: -8,
      sidebarShadow: '#00000005',
      sidebarShadowBlur: 6,
      sidebarShadowSpread: -8,
      stickyHeaderShadow: '#0000000a',
      stickyHeaderShadowBlur: 10,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#ffffff',
      pageGradientTo: '#ffffff',
      heroGradientFrom: '#f5f5f7',
      heroGradientVia: '#f5f5f7',
      heroGradientTo: '#f5f5f7',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#ffffff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#ffffff',
      tabsGradientVia: '#f5f5f7',
      tabsGradientTo: '#ffffff',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  {
    name: 'Paper',
    accent: '#6750a4',
    colors: {
      bgPrimary: '#fffbfe',
      bgSecondary: '#f7f2fa',
      panelBg: '#fffbfe',
      heroBg: '#f7f2fa',
      bgTertiary: '#ece6f0',
      bgQuaternary: '#cac4d0',
      textPrimary: '#1d1b20',
      textSecondary: '#49454f',
      textTertiary: '#79747e',
      borderPrimary: '#e7e0ec',
      borderSecondary: '#cac4d0',
      accentPrimary: '#6750a4',
      accentHover: '#4f378b',
      headerBg: '#fffbfef2',
      headerOpacity: 1,
      headerText: '#1d1b20',
      headerBlur: 0,
      headerBorder: '#e7e0ec',
      headerBorderOpacity: 1,
      headerBorderWidth: 0,
      headerMenuFontWeight: 500,
      fontFamily: 'material',
      stickyHeaderBg: '#fffbfef2',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#1d1b20',
      stickyHeaderBorder: '#e7e0ec',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 0,
      sidebarBg: '#f7f2faee',
      sidebarBorder: '#e7e0ec',
      sidebarOpacity: 1,
      headerShadow: '#1d1b200f',
      headerShadowBlur: 10,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      panelShadow: '#1d1b200d',
      panelShadowBlur: 12,
      panelShadowSpread: -4,
      cardShadow: '#1d1b201a',
      cardShadowBlur: 16,
      cardShadowSpread: -4,
      tabsShadow: '#1d1b200d',
      tabsShadowBlur: 12,
      tabsShadowSpread: -4,
      sidebarShadow: '#1d1b2010',
      sidebarShadowBlur: 10,
      sidebarShadowSpread: -12,
      stickyHeaderShadow: '#1d1b200d',
      stickyHeaderShadowBlur: 10,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#fffbfe',
      pageGradientVia: '#fcf8fd',
      pageGradientTo: '#fffbfe',
      heroGradientFrom: '#f7f2fa',
      heroGradientVia: '#f8f3fa',
      heroGradientTo: '#f7f2fa',
      cardGradientFrom: '#fffbfe',
      cardGradientVia: '#f7f2fa',
      cardGradientTo: '#fffbfe',
      tabsGradientFrom: '#fffbfe',
      tabsGradientVia: '#faf6fc',
      tabsGradientTo: '#fffbfe',
      pageGlow: '#efe7f8',
      glowOpacity: 1,
    },
  },
  {
    name: 'Clearline',
    accent: '#0f6cbd',
    colors: {
      bgPrimary: '#f3f2f1',
      bgSecondary: '#ffffff',
      panelBg: '#ffffff',
      heroBg: '#faf9f8',
      bgTertiary: '#edebe9',
      bgQuaternary: '#e1dfdd',
      textPrimary: '#201f1e',
      textSecondary: '#605e5c',
      textTertiary: '#8a8886',
      borderPrimary: '#e1dfdd',
      borderSecondary: '#c8c6c4',
      accentPrimary: '#0f6cbd',
      accentHover: '#115ea3',
      headerBg: '#ffffffd9',
      headerOpacity: 1,
      headerText: '#201f1e',
      headerBlur: 20,
      headerBorder: '#edebe9cc',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 600,
      fontFamily: 'fluent',
      stickyHeaderBg: '#ffffffe0',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 24,
      stickyHeaderText: '#201f1e',
      stickyHeaderBorder: '#edebe9cc',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f3f2f1d9',
      sidebarBorder: '#e1dfddcc',
      sidebarOpacity: 1,
      headerShadow: '#00000012',
      headerShadowBlur: 20,
      headerShadowSpread: -20,
      surfaceRadius: 6,
      statCardAccentTop: 2,
      panelShadow: '#00000010',
      panelShadowBlur: 16,
      panelShadowSpread: -12,
      cardShadow: '#00000016',
      cardShadowBlur: 16,
      cardShadowSpread: -12,
      tabsShadow: '#00000010',
      tabsShadowBlur: 16,
      tabsShadowSpread: -12,
      sidebarShadow: '#00000014',
      sidebarShadowBlur: 22,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000012',
      stickyHeaderShadowBlur: 20,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#f7f8fa',
      pageGradientVia: '#f3f6f9',
      pageGradientTo: '#f3f2f1',
      heroGradientFrom: '#ffffff',
      heroGradientVia: '#f8fafc',
      heroGradientTo: '#faf9f8',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fbfdff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#faf9f8',
      tabsGradientVia: '#f5f7fa',
      tabsGradientTo: '#faf9f8',
      pageGlow: '#d9ebfb',
      glowOpacity: 1,
    },
  },
  {
    name: 'Glassline',
    accent: '#0071e3',
    colors: {
      bgPrimary: '#f5f5f7',
      bgSecondary: '#ffffff',
      panelBg: '#ffffff',
      heroBg: '#fbfbfd',
      bgTertiary: '#f0f0f2',
      bgQuaternary: '#d2d2d7',
      textPrimary: '#1d1d1f',
      textSecondary: '#424245',
      textTertiary: '#6e6e73',
      borderPrimary: '#00000010',
      borderSecondary: '#00000018',
      accentPrimary: '#0071e3',
      accentHover: '#005bb5',
      headerBg: '#fbfbfdc7',
      headerOpacity: 1,
      headerText: '#1d1d1f',
      headerBlur: 30,
      headerBorder: '#ffffff66',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'apple',
      stickyHeaderBg: '#fbfbfdd6',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 34,
      stickyHeaderText: '#1d1d1f',
      stickyHeaderBorder: '#ffffff5c',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f5f5f7bd',
      sidebarBorder: '#ffffff55',
      sidebarOpacity: 1,
      headerShadow: '#00000012',
      headerShadowBlur: 18,
      headerShadowSpread: -20,
      surfaceRadius: 20,
      statCardAccentTop: 0,
      panelShadow: '#0000000e',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#00000014',
      cardShadowBlur: 28,
      cardShadowSpread: -8,
      tabsShadow: '#0000000e',
      tabsShadowBlur: 16,
      tabsShadowSpread: -10,
      sidebarShadow: '#00000010',
      sidebarShadowBlur: 18,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000012',
      stickyHeaderShadowBlur: 18,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#f7f7f9',
      pageGradientVia: '#f5f5f7',
      pageGradientTo: '#f2f2f4',
      heroGradientFrom: '#ffffff',
      heroGradientVia: '#fbfbfd',
      heroGradientTo: '#ffffff',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fbfbfd',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#f7f7f9',
      tabsGradientVia: '#f5f5f7',
      tabsGradientTo: '#f7f7f9',
      pageGlow: '#ffffff',
      glowOpacity: 1,
    },
  },
];

export const DARK_PRESETS: Array<{ name: string; accent: string; colors: PartialColorTokens }> = [
  {
    name: 'Default',
    accent: DEFAULT_DARK_COLORS.accentPrimary,
    colors: DEFAULT_DARK_COLORS,
  },
  // ── Gridline Dark ─────────────────────────────────────────────────────
  // Flat, no glow, no gradients · 0 radius · visible white-10 borders ·
  // solid opaque header · left accent 4 px · cool gray 100/90/80 scale
  {
    name: 'Gridline',
    accent: '#78a9ff',
    colors: {
      bgPrimary: '#161616',
      bgSecondary: '#262626',
      panelBg: '#262626',
      heroBg: '#1e1e1e',
      bgTertiary: '#393939',
      bgQuaternary: '#525252',
      textPrimary: '#f4f4f4',
      textSecondary: '#c6c6c6',
      textTertiary: '#8d8d8d',
      borderPrimary: '#393939',
      borderSecondary: '#525252',
      accentPrimary: '#78a9ff',
      accentHover: '#a6c8ff',
      headerBg: '#161616f8',
      headerOpacity: 1,
      headerText: '#f4f4f4',
      headerBlur: 0,
      headerBorder: '#393939',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 400,
      fontFamily: 'carbon',
      stickyHeaderBg: '#161616f8',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#f4f4f4',
      stickyHeaderBorder: '#393939',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#1e1e1ef5',
      sidebarBorder: '#393939',
      sidebarOpacity: 1,
      headerShadow: '#00000000',
      headerShadowBlur: 0,
      headerShadowSpread: 0,
      surfaceRadius: 0,
      statCardAccentTop: 0,
      statCardAccentLeft: 4,
      panelShadow: '#00000000',
      panelShadowBlur: 0,
      panelShadowSpread: 0,
      cardShadow: '#00000000',
      cardShadowBlur: 0,
      cardShadowSpread: 0,
      tabsShadow: '#00000000',
      tabsShadowBlur: 0,
      tabsShadowSpread: 0,
      sidebarShadow: '#00000000',
      sidebarShadowBlur: 0,
      sidebarShadowSpread: 0,
      stickyHeaderShadow: '#00000000',
      stickyHeaderShadowBlur: 0,
      stickyHeaderShadowSpread: 0,
      pageGradientFrom: '#161616',
      pageGradientVia: '#161616',
      pageGradientTo: '#161616',
      heroGradientFrom: '#1e1e1e',
      heroGradientVia: '#1e1e1e',
      heroGradientTo: '#1e1e1e',
      cardGradientFrom: '#262626',
      cardGradientVia: '#262626',
      cardGradientTo: '#262626',
      tabsGradientFrom: '#161616',
      tabsGradientVia: '#161616',
      tabsGradientTo: '#161616',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Evergreen Dark ────────────────────────────────────────────────────
  // Warm charcoal base · soft card shadows · 8 px radius · solid
  // header · green accent · no glow · top accent 3 px
  {
    name: 'Evergreen',
    accent: '#36a977',
    colors: {
      bgPrimary: '#1a1a1a',
      bgSecondary: '#252525',
      panelBg: '#2a2a2a',
      heroBg: '#202020',
      bgTertiary: '#333333',
      bgQuaternary: '#474747',
      textPrimary: '#e3e5e7',
      textSecondary: '#999ca0',
      textTertiary: '#72767a',
      borderPrimary: '#3d3d3d',
      borderSecondary: '#575757',
      accentPrimary: '#36a977',
      accentHover: '#2e9268',
      headerBg: '#1a1a1af0',
      headerOpacity: 1,
      headerText: '#e3e5e7',
      headerBlur: 0,
      headerBorder: '#3d3d3d',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'polaris',
      stickyHeaderBg: '#1a1a1af5',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#e3e5e7',
      stickyHeaderBorder: '#3d3d3d',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#202020f0',
      sidebarBorder: '#3d3d3d',
      sidebarOpacity: 1,
      headerShadow: '#00000018',
      headerShadowBlur: 6,
      headerShadowSpread: -4,
      surfaceRadius: 8,
      statCardAccentTop: 2,
      statCardAccentLeft: 0,
      panelShadow: '#00000020',
      panelShadowBlur: 8,
      panelShadowSpread: -4,
      cardShadow: '#0000002a',
      cardShadowBlur: 10,
      cardShadowSpread: -4,
      tabsShadow: '#0000001a',
      tabsShadowBlur: 8,
      tabsShadowSpread: -4,
      sidebarShadow: '#00000016',
      sidebarShadowBlur: 6,
      sidebarShadowSpread: -6,
      stickyHeaderShadow: '#00000018',
      stickyHeaderShadowBlur: 6,
      stickyHeaderShadowSpread: -4,
      pageGradientFrom: '#1a1a1a',
      pageGradientVia: '#1a1a1a',
      pageGradientTo: '#1a1a1a',
      heroGradientFrom: '#202020',
      heroGradientVia: '#202020',
      heroGradientTo: '#202020',
      cardGradientFrom: '#252525',
      cardGradientVia: '#2a2a2a',
      cardGradientTo: '#252525',
      tabsGradientFrom: '#1a1a1a',
      tabsGradientVia: '#1a1a1a',
      tabsGradientTo: '#1a1a1a',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Keystone Dark ─────────────────────────────────────────────────────
  // Cool neutral dark · 6 px radius · medium shadows · blue accent
  // (#1668dc) · solid header with subtle border · no glow · top
  // accent 2 px
  {
    name: 'Keystone',
    accent: '#1668dc',
    colors: {
      bgPrimary: '#141414',
      bgSecondary: '#1f1f1f',
      panelBg: '#1f1f1f',
      heroBg: '#1a1a1a',
      bgTertiary: '#2a2a2a',
      bgQuaternary: '#3a3a3a',
      textPrimary: '#ffffffd9',
      textSecondary: '#ffffff80',
      textTertiary: '#ffffff4d',
      borderPrimary: '#303030',
      borderSecondary: '#434343',
      accentPrimary: '#1668dc',
      accentHover: '#3c89e8',
      headerBg: '#141414f8',
      headerOpacity: 1,
      headerText: '#ffffffd9',
      headerBlur: 0,
      headerBorder: '#303030',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'ant',
      stickyHeaderBg: '#141414f8',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#ffffffd9',
      stickyHeaderBorder: '#303030',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#1a1a1a',
      sidebarBorder: '#303030',
      sidebarOpacity: 1,
      headerShadow: '#0000001a',
      headerShadowBlur: 8,
      headerShadowSpread: -6,
      surfaceRadius: 6,
      statCardAccentTop: 2,
      statCardAccentLeft: 0,
      panelShadow: '#00000020',
      panelShadowBlur: 10,
      panelShadowSpread: -4,
      cardShadow: '#0000002a',
      cardShadowBlur: 14,
      cardShadowSpread: -4,
      tabsShadow: '#0000001a',
      tabsShadowBlur: 10,
      tabsShadowSpread: -6,
      sidebarShadow: '#00000016',
      sidebarShadowBlur: 8,
      sidebarShadowSpread: -8,
      stickyHeaderShadow: '#0000001a',
      stickyHeaderShadowBlur: 8,
      stickyHeaderShadowSpread: -6,
      pageGradientFrom: '#141414',
      pageGradientVia: '#141414',
      pageGradientTo: '#141414',
      heroGradientFrom: '#1a1a1a',
      heroGradientVia: '#1f1f1f',
      heroGradientTo: '#1a1a1a',
      cardGradientFrom: '#1f1f1f',
      cardGradientVia: '#232323',
      cardGradientTo: '#1f1f1f',
      tabsGradientFrom: '#141414',
      tabsGradientVia: '#141414',
      tabsGradientTo: '#141414',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Prism Dark ────────────────────────────────────────────────────────
  // Deep gray base · 4 px radius · moderate shadows · blue accent ·
  // header blur 16 · left accent 3 px · no glow
  {
    name: 'Prism',
    accent: '#2680eb',
    colors: {
      bgPrimary: '#1e1e1e',
      bgSecondary: '#2c2c2c',
      panelBg: '#2c2c2c',
      heroBg: '#252525',
      bgTertiary: '#3e3e3e',
      bgQuaternary: '#505050',
      textPrimary: '#e1e1e1',
      textSecondary: '#b3b3b3',
      textTertiary: '#8e8e8e',
      borderPrimary: '#3e3e3e',
      borderSecondary: '#545454',
      accentPrimary: '#2680eb',
      accentHover: '#378ef0',
      headerBg: '#1e1e1ed0',
      headerOpacity: 1,
      headerText: '#e1e1e1',
      headerBlur: 16,
      headerBorder: '#3e3e3ea0',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'spectrum',
      stickyHeaderBg: '#1e1e1ed8',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 16,
      stickyHeaderText: '#e1e1e1',
      stickyHeaderBorder: '#3e3e3e90',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#252525e0',
      sidebarBorder: '#3e3e3e',
      sidebarOpacity: 1,
      headerShadow: '#00000020',
      headerShadowBlur: 14,
      headerShadowSpread: -10,
      surfaceRadius: 4,
      statCardAccentTop: 0,
      statCardAccentLeft: 3,
      panelShadow: '#00000020',
      panelShadowBlur: 12,
      panelShadowSpread: -6,
      cardShadow: '#0000002a',
      cardShadowBlur: 18,
      cardShadowSpread: -6,
      tabsShadow: '#0000001a',
      tabsShadowBlur: 12,
      tabsShadowSpread: -6,
      sidebarShadow: '#00000018',
      sidebarShadowBlur: 10,
      sidebarShadowSpread: -10,
      stickyHeaderShadow: '#00000022',
      stickyHeaderShadowBlur: 14,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#1e1e1e',
      pageGradientVia: '#212121',
      pageGradientTo: '#1e1e1e',
      heroGradientFrom: '#252525',
      heroGradientVia: '#282828',
      heroGradientTo: '#252525',
      cardGradientFrom: '#2c2c2c',
      cardGradientVia: '#303030',
      cardGradientTo: '#2c2c2c',
      tabsGradientFrom: '#1e1e1e',
      tabsGradientVia: '#222222',
      tabsGradientTo: '#1e1e1e',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Baseline Dark ─────────────────────────────────────────────────────
  // Signature GitHub dark · 6 px radius · subtle shadows · blue
  // accent · solid header with bottom border · no glow · no accents
  {
    name: 'Baseline',
    accent: '#58a6ff',
    colors: {
      bgPrimary: '#0d1117',
      bgSecondary: '#161b22',
      panelBg: '#161b22',
      heroBg: '#10161d',
      bgTertiary: '#21262d',
      bgQuaternary: '#30363d',
      textPrimary: '#e6edf3',
      textSecondary: '#8b949e',
      textTertiary: '#6e7681',
      borderPrimary: '#30363d',
      borderSecondary: '#484f58',
      accentPrimary: '#58a6ff',
      accentHover: '#79c0ff',
      headerBg: '#0d1117f0',
      headerOpacity: 1,
      headerText: '#e6edf3',
      headerBlur: 0,
      headerBorder: '#30363d',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'system',
      stickyHeaderBg: '#0d1117f5',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#e6edf3',
      stickyHeaderBorder: '#30363d',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#10161df0',
      sidebarBorder: '#30363d',
      sidebarOpacity: 1,
      headerShadow: '#0000001a',
      headerShadowBlur: 6,
      headerShadowSpread: -4,
      surfaceRadius: 6,
      statCardAccentTop: 0,
      statCardAccentLeft: 0,
      panelShadow: '#0000001e',
      panelShadowBlur: 8,
      panelShadowSpread: -4,
      cardShadow: '#00000028',
      cardShadowBlur: 10,
      cardShadowSpread: -4,
      tabsShadow: '#0000001a',
      tabsShadowBlur: 8,
      tabsShadowSpread: -4,
      sidebarShadow: '#00000016',
      sidebarShadowBlur: 6,
      sidebarShadowSpread: -6,
      stickyHeaderShadow: '#0000001a',
      stickyHeaderShadowBlur: 6,
      stickyHeaderShadowSpread: -4,
      pageGradientFrom: '#0d1117',
      pageGradientVia: '#0d1117',
      pageGradientTo: '#0d1117',
      heroGradientFrom: '#10161d',
      heroGradientVia: '#10161d',
      heroGradientTo: '#10161d',
      cardGradientFrom: '#161b22',
      cardGradientVia: '#161b22',
      cardGradientTo: '#161b22',
      tabsGradientFrom: '#0d1117',
      tabsGradientVia: '#0d1117',
      tabsGradientTo: '#0d1117',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  // ── Monochrome Dark ───────────────────────────────────────────────────
  // Apple HIG dark · 12 px radius · elevated surfaces · glass
  // header (blur 20) · blue-gray tinted grays · no glow ·
  // system-gray accent for button contrast
  {
    name: 'Monochrome',
    accent: '#8e8e93',
    colors: {
      bgPrimary: '#000000',
      bgSecondary: '#1c1c1e',
      panelBg: '#1c1c1e',
      heroBg: '#0a0a0a',
      bgTertiary: '#2c2c2e',
      bgQuaternary: '#3a3a3c',
      textPrimary: '#f5f5f7',
      textSecondary: '#98989d',
      textTertiary: '#636366',
      borderPrimary: '#38383a',
      borderSecondary: '#48484a',
      accentPrimary: '#8e8e93',
      accentHover: '#787880',
      headerBg: '#1c1c1ea0',
      headerOpacity: 1,
      headerText: '#f5f5f7',
      headerBlur: 20,
      headerBorder: '#38383a90',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 400,
      fontFamily: 'geist',
      stickyHeaderBg: '#000000c0',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 20,
      stickyHeaderText: '#f5f5f7',
      stickyHeaderBorder: '#38383a80',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#1c1c1e90',
      sidebarBorder: '#38383a80',
      sidebarOpacity: 1,
      headerShadow: '#00000020',
      headerShadowBlur: 10,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      statCardAccentLeft: 0,
      panelShadow: '#00000020',
      panelShadowBlur: 8,
      panelShadowSpread: -8,
      cardShadow: '#00000028',
      cardShadowBlur: 12,
      cardShadowSpread: -8,
      tabsShadow: '#00000018',
      tabsShadowBlur: 8,
      tabsShadowSpread: -8,
      sidebarShadow: '#00000015',
      sidebarShadowBlur: 8,
      sidebarShadowSpread: -10,
      stickyHeaderShadow: '#00000020',
      stickyHeaderShadowBlur: 10,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#000000',
      pageGradientVia: '#000000',
      pageGradientTo: '#000000',
      heroGradientFrom: '#0a0a0a',
      heroGradientVia: '#0a0a0a',
      heroGradientTo: '#0a0a0a',
      cardGradientFrom: '#1c1c1e',
      cardGradientVia: '#1c1c1e',
      cardGradientTo: '#1c1c1e',
      tabsGradientFrom: '#1c1c1e',
      tabsGradientVia: '#1c1c1e',
      tabsGradientTo: '#1c1c1e',
      pageGlow: '#00000000',
      glowOpacity: 0,
    },
  },
  {
    name: 'Paper',
    accent: '#d0bcff',
    colors: {
      bgPrimary: '#141218',
      bgSecondary: '#1d1b20',
      panelBg: '#211f26',
      heroBg: '#1d1b20',
      bgTertiary: '#2b2930',
      bgQuaternary: '#49454f',
      textPrimary: '#e6e1e5',
      textSecondary: '#cac4d0',
      textTertiary: '#938f99',
      borderPrimary: '#49454f80',
      borderSecondary: '#938f99',
      accentPrimary: '#d0bcff',
      accentHover: '#b69df8',
      headerBg: '#1d1b20f2',
      headerOpacity: 1,
      headerText: '#e6e1e5',
      headerBlur: 0,
      headerBorder: '#49454f80',
      headerBorderOpacity: 1,
      headerBorderWidth: 0,
      headerMenuFontWeight: 500,
      fontFamily: 'material',
      stickyHeaderBg: '#1d1b20f5',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#e6e1e5',
      stickyHeaderBorder: '#49454f80',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 0,
      sidebarBg: '#1d1b20eb',
      sidebarBorder: '#49454f80',
      sidebarOpacity: 1,
      headerShadow: '#00000024',
      headerShadowBlur: 12,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      panelShadow: '#0000002a',
      panelShadowBlur: 12,
      panelShadowSpread: -4,
      cardShadow: '#00000035',
      cardShadowBlur: 16,
      cardShadowSpread: -4,
      tabsShadow: '#0000002a',
      tabsShadowBlur: 12,
      tabsShadowSpread: -4,
      sidebarShadow: '#00000028',
      sidebarShadowBlur: 12,
      sidebarShadowSpread: -14,
      stickyHeaderShadow: '#00000026',
      stickyHeaderShadowBlur: 12,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#141218',
      pageGradientVia: '#17141c',
      pageGradientTo: '#141218',
      heroGradientFrom: '#1d1b20',
      heroGradientVia: '#211f26',
      heroGradientTo: '#1d1b20',
      cardGradientFrom: '#211f26',
      cardGradientVia: '#2b2930',
      cardGradientTo: '#211f26',
      tabsGradientFrom: '#1d1b20',
      tabsGradientVia: '#221f27',
      tabsGradientTo: '#1d1b20',
      pageGlow: '#141218',
      glowOpacity: 1,
    },
  },
  {
    name: 'Clearline',
    accent: '#60cdff',
    colors: {
      bgPrimary: '#1b1a19',
      bgSecondary: '#201f1e',
      panelBg: '#252423',
      heroBg: '#242322',
      bgTertiary: '#323130',
      bgQuaternary: '#484644',
      textPrimary: '#f3f2f1',
      textSecondary: '#c8c6c4',
      textTertiary: '#a19f9d',
      borderPrimary: '#3b3a39',
      borderSecondary: '#605e5c',
      accentPrimary: '#60cdff',
      accentHover: '#4cc2ff',
      headerBg: '#201f1ecc',
      headerOpacity: 1,
      headerText: '#f3f2f1',
      headerBlur: 20,
      headerBorder: '#3b3a39c8',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 600,
      fontFamily: 'fluent',
      stickyHeaderBg: '#201f1ed9',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 24,
      stickyHeaderText: '#f3f2f1',
      stickyHeaderBorder: '#3b3a39d4',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#252423cc',
      sidebarBorder: '#3b3a39cc',
      sidebarOpacity: 1,
      headerShadow: '#00000028',
      headerShadowBlur: 20,
      headerShadowSpread: -20,
      surfaceRadius: 6,
      statCardAccentTop: 2,
      panelShadow: '#00000026',
      panelShadowBlur: 18,
      panelShadowSpread: -12,
      cardShadow: '#00000035',
      cardShadowBlur: 16,
      cardShadowSpread: -12,
      tabsShadow: '#00000024',
      tabsShadowBlur: 18,
      tabsShadowSpread: -12,
      sidebarShadow: '#00000030',
      sidebarShadowBlur: 22,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#0000002c',
      stickyHeaderShadowBlur: 20,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#1b1a19',
      pageGradientVia: '#1f252c',
      pageGradientTo: '#1b1a19',
      heroGradientFrom: '#252423',
      heroGradientVia: '#242b34',
      heroGradientTo: '#252423',
      cardGradientFrom: '#252423',
      cardGradientVia: '#232a33',
      cardGradientTo: '#252423',
      tabsGradientFrom: '#201f1e',
      tabsGradientVia: '#20262f',
      tabsGradientTo: '#201f1e',
      pageGlow: '#0f6cbd33',
      glowOpacity: 1,
    },
  },
  {
    name: 'Glassline',
    accent: '#0a84ff',
    colors: {
      bgPrimary: '#0b0b0f',
      bgSecondary: '#1c1c1e',
      panelBg: '#1c1c1e',
      heroBg: '#161618',
      bgTertiary: '#2c2c2e',
      bgQuaternary: '#3a3a3c',
      textPrimary: '#f5f5f7',
      textSecondary: '#d1d1d6',
      textTertiary: '#8e8e93',
      borderPrimary: '#ffffff10',
      borderSecondary: '#ffffff18',
      accentPrimary: '#0a84ff',
      accentHover: '#409cff',
      headerBg: '#1c1c1eb8',
      headerOpacity: 1,
      headerText: '#f5f5f7',
      headerBlur: 30,
      headerBorder: '#ffffff12',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'apple',
      stickyHeaderBg: '#1c1c1ecc',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 34,
      stickyHeaderText: '#f5f5f7',
      stickyHeaderBorder: '#ffffff10',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#161618c7',
      sidebarBorder: '#ffffff10',
      sidebarOpacity: 1,
      headerShadow: '#00000024',
      headerShadowBlur: 18,
      headerShadowSpread: -20,
      surfaceRadius: 20,
      statCardAccentTop: 0,
      panelShadow: '#00000025',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#00000035',
      cardShadowBlur: 28,
      cardShadowSpread: -8,
      tabsShadow: '#00000025',
      tabsShadowBlur: 14,
      tabsShadowSpread: -10,
      sidebarShadow: '#00000022',
      sidebarShadowBlur: 18,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000028',
      stickyHeaderShadowBlur: 18,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#0b0b0f',
      pageGradientVia: '#111216',
      pageGradientTo: '#0b0b0f',
      heroGradientFrom: '#161618',
      heroGradientVia: '#1c1c20',
      heroGradientTo: '#161618',
      cardGradientFrom: '#1f1f22',
      cardGradientVia: '#1c1c1f',
      cardGradientTo: '#1f1f22',
      tabsGradientFrom: '#111216',
      tabsGradientVia: '#15161a',
      tabsGradientTo: '#111216',
      pageGlow: '#0a84ff18',
      glowOpacity: 1,
    },
  },
];
