// Client-side theme palette types/defaults used by the admin theme editor.

export type ColorHexKey =
  | 'bgPrimary'
  | 'bgSecondary'
  | 'panelBg'
  | 'bgTertiary'
  | 'bgQuaternary'
  | 'textPrimary'
  | 'textSecondary'
  | 'textTertiary'
  | 'borderPrimary'
  | 'borderSecondary'
  | 'accentPrimary'
  | 'accentHover'
  | 'headerBg'
  | 'headerText'
  | 'headerBorder'
  | 'stickyHeaderBg'
  | 'stickyHeaderText'
  | 'stickyHeaderBorder'
  | 'sidebarBg'
  | 'sidebarBorder'
  | 'headerShadow'
  | 'panelShadow'
  | 'cardShadow'
  | 'tabsShadow'
  | 'sidebarShadow'
  // Sticky header shadow is configured in Layout tab (not in the Colors tab).
  | 'pageGradientFrom'
  | 'pageGradientVia'
  | 'pageGradientTo'
  | 'cardGradientFrom'
  | 'cardGradientVia'
  | 'cardGradientTo'
  | 'tabsGradientFrom'
  | 'tabsGradientVia'
  | 'tabsGradientTo'
  | 'pageGlow';

export type OpacityKey =
  | 'headerOpacity'
  | 'sidebarOpacity'
  | 'glowOpacity'
  | 'headerBorderOpacity'
  | 'stickyHeaderBorderOpacity';

export type ThemeFontFamily = 'system' | 'material' | 'fluent' | 'apple';

export type ColorTokens = {
  bgPrimary: string;
  bgSecondary: string;
  panelBg: string;
  heroBg: string;
  bgTertiary: string;
  bgQuaternary: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  borderPrimary: string;
  borderSecondary: string;
  accentPrimary: string;
  accentHover: string;
  headerBg: string;
  headerOpacity: number;
  headerText: string;
  headerBlur: number;
  headerBorder: string;
  headerBorderOpacity: number;
  headerBorderWidth: number;
  headerMenuFontSize: number;
  headerMenuFontWeight: number;
  fontFamily: ThemeFontFamily;
  stickyHeaderBg: string;
  stickyHeaderOpacity: number;
  stickyHeaderBlur: number;
  stickyHeaderText: string;
  stickyHeaderBorder: string;
  stickyHeaderBorderOpacity: number;
  stickyHeaderBorderWidth: number;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarOpacity: number;
  headerShadow: string;
  headerShadowBlur: number;
  headerShadowSpread: number;
  surfaceRadius: number;
  statCardAccentTop: number;
  statCardAccentLeft: number;
  panelShadow: string;
  panelShadowBlur: number;
  panelShadowSpread: number;
  cardShadow: string;
  cardShadowBlur: number;
  cardShadowSpread: number;
  tabsShadow: string;
  tabsShadowBlur: number;
  tabsShadowSpread: number;
  sidebarShadow: string;
  sidebarShadowBlur: number;
  sidebarShadowSpread: number;
  stickyHeaderShadow: string;
  stickyHeaderShadowBlur: number;
  stickyHeaderShadowSpread: number;
  pageGradientFrom: string;
  pageGradientVia: string;
  pageGradientTo: string;
  heroGradientFrom: string;
  heroGradientVia: string;
  heroGradientTo: string;
  cardGradientFrom: string;
  cardGradientVia: string;
  cardGradientTo: string;
  tabsGradientFrom: string;
  tabsGradientVia: string;
  tabsGradientTo: string;
  pageGlow: string;
  glowOpacity: number;
};

type ElementGradientKeys =
  | 'heroGradientFrom'
  | 'heroGradientVia'
  | 'heroGradientTo'
  | 'cardGradientFrom'
  | 'cardGradientVia'
  | 'cardGradientTo'
  | 'tabsGradientFrom'
  | 'tabsGradientVia'
  | 'tabsGradientTo';

type OptionalPresetKeys =
  | ElementGradientKeys
  | 'headerText'
  | 'headerBlur'
  | 'headerBorder'
  | 'headerBorderOpacity'
  | 'headerBorderWidth'
  | 'stickyHeaderBg'
  | 'stickyHeaderOpacity'
  | 'stickyHeaderBlur'
  | 'stickyHeaderText'
  | 'stickyHeaderBorder'
  | 'stickyHeaderBorderOpacity'
  | 'stickyHeaderBorderWidth';

// Optional across presets so existing built-ins don't need updates.
type OptionalEffectKeys =
  | 'sidebarBorder'
  | 'headerShadow'
  | 'headerShadowBlur'
  | 'headerShadowSpread'
  | 'surfaceRadius'
  | 'statCardAccentTop'
  | 'statCardAccentLeft'
  | 'panelShadow'
  | 'panelShadowBlur'
  | 'panelShadowSpread'
  | 'cardShadow'
  | 'cardShadowBlur'
  | 'cardShadowSpread'
  | 'tabsShadow'
  | 'tabsShadowBlur'
  | 'tabsShadowSpread'
  | 'sidebarShadow'
  | 'sidebarShadowBlur'
  | 'sidebarShadowSpread'
  | 'stickyHeaderShadow'
  | 'stickyHeaderShadowBlur'
  | 'stickyHeaderShadowSpread'
  | 'headerMenuFontSize'
  | 'headerMenuFontWeight'
  | 'fontFamily';

const sanitizeThemeFontFamily = (value: unknown, fallback: ThemeFontFamily): ThemeFontFamily => {
  return value === 'material' || value === 'fluent' || value === 'apple' || value === 'system'
    ? value
    : fallback;
};

export type PartialColorTokens = Omit<ColorTokens, OptionalPresetKeys | OptionalEffectKeys> &
  Partial<Pick<ColorTokens, OptionalPresetKeys | OptionalEffectKeys>>;

export const fillElementGradients = (t: PartialColorTokens): ColorTokens => {
  const clampInt = (n: unknown, min: number, max: number, fallback: number) => {
    const num = typeof n === 'number' ? n : typeof n === 'string' ? Number(n) : NaN;
    if (!Number.isFinite(num)) return fallback;
    return Math.max(min, Math.min(max, Math.round(num)));
  };

  return {
    ...(t as Omit<ColorTokens, ElementGradientKeys>),
    headerText: t.headerText ?? t.textPrimary,
    headerBlur: typeof t.headerBlur === 'number' ? t.headerBlur : 12,
    headerBorder: t.headerBorder ?? t.borderPrimary,
    headerBorderOpacity: typeof t.headerBorderOpacity === 'number' ? t.headerBorderOpacity : 1,
    headerBorderWidth: typeof t.headerBorderWidth === 'number' ? t.headerBorderWidth : 1,
    headerMenuFontSize: clampInt(t.headerMenuFontSize, 10, 20, 14),
    headerMenuFontWeight: clampInt(t.headerMenuFontWeight, 300, 800, 400),
    fontFamily: sanitizeThemeFontFamily(t.fontFamily, 'system'),
    stickyHeaderBg: t.stickyHeaderBg ?? t.headerBg,
    stickyHeaderOpacity: typeof t.stickyHeaderOpacity === 'number' ? t.stickyHeaderOpacity : 1,
    stickyHeaderBlur: typeof t.stickyHeaderBlur === 'number' ? t.stickyHeaderBlur : 14,
    stickyHeaderText: t.stickyHeaderText ?? t.headerText ?? t.textPrimary,
    stickyHeaderBorder: t.stickyHeaderBorder ?? t.headerBorder ?? t.borderPrimary,
    stickyHeaderBorderOpacity: typeof t.stickyHeaderBorderOpacity === 'number' ? t.stickyHeaderBorderOpacity : 1,
    stickyHeaderBorderWidth:
      typeof t.stickyHeaderBorderWidth === 'number'
        ? t.stickyHeaderBorderWidth
        : typeof t.headerBorderWidth === 'number'
          ? t.headerBorderWidth
          : 1,
    sidebarBorder: t.sidebarBorder ?? t.borderPrimary,
    headerShadow: t.headerShadow ?? '#00000014',
    headerShadowBlur: clampInt(t.headerShadowBlur, 0, 80, 30),
    headerShadowSpread: clampInt(t.headerShadowSpread, -80, 80, -22),
    surfaceRadius: clampInt(t.surfaceRadius, 0, 32, 16),
    statCardAccentTop: clampInt(t.statCardAccentTop, 0, 8, 0),
    statCardAccentLeft: clampInt(t.statCardAccentLeft, 0, 8, 0),
    panelShadow: t.panelShadow ?? t.cardShadow ?? '#00000012',
    panelShadowBlur: clampInt(t.panelShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    panelShadowSpread: clampInt(t.panelShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    cardShadow: t.cardShadow ?? '#00000014',
    cardShadowBlur: clampInt(t.cardShadowBlur, 0, 80, 24),
    cardShadowSpread: clampInt(t.cardShadowSpread, -80, 80, -18),
    tabsShadow: t.tabsShadow ?? t.cardShadow ?? '#00000010',
    tabsShadowBlur: clampInt(t.tabsShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    tabsShadowSpread: clampInt(t.tabsShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    sidebarShadow: t.sidebarShadow ?? t.panelShadow ?? t.headerShadow ?? '#00000010',
    sidebarShadowBlur: clampInt(
      t.sidebarShadowBlur,
      0,
      80,
      clampInt(t.panelShadowBlur, 0, 80, clampInt(t.cardShadowBlur, 0, 80, 24)),
    ),
    sidebarShadowSpread: clampInt(
      t.sidebarShadowSpread,
      -80,
      80,
      clampInt(t.panelShadowSpread, -80, 80, clampInt(t.cardShadowSpread, -80, 80, -18)),
    ),
    stickyHeaderShadow: t.stickyHeaderShadow ?? t.headerShadow ?? '#00000014',
    stickyHeaderShadowBlur: clampInt(t.stickyHeaderShadowBlur, 0, 80, clampInt(t.headerShadowBlur, 0, 80, 30)),
    stickyHeaderShadowSpread: clampInt(
      t.stickyHeaderShadowSpread,
      -80,
      80,
      clampInt(t.headerShadowSpread, -80, 80, -22),
    ),
    heroGradientFrom: t.heroGradientFrom ?? t.pageGradientFrom,
    heroGradientVia: t.heroGradientVia ?? t.pageGradientVia,
    heroGradientTo: t.heroGradientTo ?? t.pageGradientTo,
    cardGradientFrom: t.cardGradientFrom ?? t.pageGradientFrom,
    cardGradientVia: t.cardGradientVia ?? t.pageGradientVia,
    cardGradientTo: t.cardGradientTo ?? t.pageGradientTo,
    tabsGradientFrom: t.tabsGradientFrom ?? t.pageGradientFrom,
    tabsGradientVia: t.tabsGradientVia ?? t.pageGradientVia,
    tabsGradientTo: t.tabsGradientTo ?? t.pageGradientTo,
  };
};

export type ThemeColorPalette = { light: ColorTokens; dark: ColorTokens };

export type ThemeColorPreset = { name: string; light: ColorTokens; dark: ColorTokens };

export const DEFAULT_LIGHT_COLORS: ColorTokens = {
  bgPrimary: '#ffffff',
  bgSecondary: '#f9fafb',
  panelBg: '#f9fafb',
  heroBg: '#f9fafb',
  bgTertiary: '#f3f4f6',
  bgQuaternary: '#e5e7eb',
  textPrimary: '#111827',
  textSecondary: '#4b5563',
  textTertiary: '#6b7280',
  borderPrimary: '#d1d5db',
  borderSecondary: '#9ca3af',
  accentPrimary: '#3b82f6',
  accentHover: '#2563eb',
  headerBg: '#ffffff37',
  headerOpacity: 1,
  headerText: '#111827',
  headerBlur: 20,
  headerBorder: '#d1d5db4c',
  headerBorderOpacity: 1,
  headerBorderWidth: 1,
  headerMenuFontSize: 14,
  headerMenuFontWeight: 600,
  fontFamily: 'system',
  stickyHeaderBg: '#ffffff3e',
  stickyHeaderOpacity: 1,
  stickyHeaderBlur: 15,
  stickyHeaderText: '#111827',
  stickyHeaderBorder: '#cccfd420',
  stickyHeaderBorderOpacity: 1,
  stickyHeaderBorderWidth: 1,
  sidebarBg: '#ffffff80',
  sidebarBorder: '#ececec6c',
  sidebarOpacity: 1,
  headerShadow: '#00000062',
  headerShadowBlur: 30,
  headerShadowSpread: -27,
  surfaceRadius: 16,
  statCardAccentTop: 0,
  statCardAccentLeft: 0,
  panelShadow: '#0f172a10',
  panelShadowBlur: 18,
  panelShadowSpread: -18,
  cardShadow: '#0f172a12',
  cardShadowBlur: 24,
  cardShadowSpread: -18,
  tabsShadow: '#0f172a10',
  tabsShadowBlur: 20,
  tabsShadowSpread: -16,
  sidebarShadow: '#0f172a14',
  sidebarShadowBlur: 22,
  sidebarShadowSpread: -20,
  stickyHeaderShadow: '#9e9c9cef',
  stickyHeaderShadowBlur: 30,
  stickyHeaderShadowSpread: -23,
  pageGradientFrom: '#ffffff',
  pageGradientVia: '#d8ecfa',
  pageGradientTo: '#ffffff',
  heroGradientFrom: '#f0f9ff00',
  heroGradientVia: '#eef2ff',
  heroGradientTo: '#ffffff',
  cardGradientFrom: '#f0f9ff',
  cardGradientVia: '#eef2ff',
  cardGradientTo: '#ffffff',
  tabsGradientFrom: '#ffffff',
  tabsGradientVia: '#eef2ff',
  tabsGradientTo: '#ffffff',
  pageGlow: '#3b82f673',
  glowOpacity: 1,
};

export const DEFAULT_DARK_COLORS: ColorTokens = {
  bgPrimary: '#0a0a0a',
  bgSecondary: '#171717',
  panelBg: '#171717',
  heroBg: '#171717',
  bgTertiary: '#262626',
  bgQuaternary: '#404040',
  textPrimary: '#f5f5f5',
  textSecondary: '#a3a3a3',
  textTertiary: '#737373',
  borderPrimary: '#4040407f',
  borderSecondary: '#4d4d4dc3',
  accentPrimary: '#3b82f6',
  accentHover: '#2563eb',
  headerBg: '#0a0a0a3e',
  headerOpacity: 1,
  headerText: '#f5f5f5',
  headerBlur: 12,
  headerBorder: '#31313179',
  headerBorderOpacity: 1,
  headerBorderWidth: 1,
  headerMenuFontSize: 14,
  headerMenuFontWeight: 600,
  fontFamily: 'system',
  stickyHeaderBg: '#0a0a0a35',
  stickyHeaderOpacity: 1,
  stickyHeaderBlur: 15,
  stickyHeaderText: '#f5f5f5',
  stickyHeaderBorder: '#40404000',
  stickyHeaderBorderOpacity: 1,
  stickyHeaderBorderWidth: 1,
  sidebarBg: '#1717175d',
  sidebarBorder: '#40404000',
  sidebarOpacity: 1,
  headerShadow: '#8e8e8e61',
  headerShadowBlur: 30,
  headerShadowSpread: -23,
  surfaceRadius: 16,
  statCardAccentTop: 0,
  statCardAccentLeft: 0,
  panelShadow: '#00000040',
  panelShadowBlur: 18,
  panelShadowSpread: -18,
  cardShadow: '#00000052',
  cardShadowBlur: 26,
  cardShadowSpread: -18,
  tabsShadow: '#00000042',
  tabsShadowBlur: 22,
  tabsShadowSpread: -16,
  sidebarShadow: '#0000004f',
  sidebarShadowBlur: 24,
  sidebarShadowSpread: -22,
  stickyHeaderShadow: '#6f6f6f7d',
  stickyHeaderShadowBlur: 30,
  stickyHeaderShadowSpread: -19,
  pageGradientFrom: '#171717',
  pageGradientVia: '#312e81',
  pageGradientTo: '#0a0a0a',
  heroGradientFrom: '#171717',
  heroGradientVia: '#312e81',
  heroGradientTo: '#0a0a0a',
  cardGradientFrom: '#171717',
  cardGradientVia: '#312e81',
  cardGradientTo: '#0a0a0a',
  tabsGradientFrom: '#171717',
  tabsGradientVia: '#312e81',
  tabsGradientTo: '#0a0a0a',
  pageGlow: '#6366f1c7',
  glowOpacity: 1,
};

export const COLOR_LABELS: Record<ColorHexKey, string> = {
  bgPrimary: 'Base background',
  bgSecondary: 'Stat / info cards',
  panelBg: 'Panels',
  bgTertiary: 'Input fields',
  bgQuaternary: 'Hover fills',
  textPrimary: 'Primary text',
  textSecondary: 'Secondary text',
  textTertiary: 'Placeholder text',
  borderPrimary: 'Primary border',
  borderSecondary: 'Secondary border',
  accentPrimary: 'Primary accent',
  accentHover: 'Accent hover',
  headerBg: 'Header background',
  headerText: 'Header text',
  headerBorder: 'Header border (bottom)',
  stickyHeaderBg: 'Sticky header background',
  stickyHeaderText: 'Sticky header text',
  stickyHeaderBorder: 'Sticky header border (bottom)',
  sidebarBg: 'Sidebar background',
  sidebarBorder: 'Sidebar border',
  headerShadow: 'Header drop shadow',
  panelShadow: 'Panel shadow',
  cardShadow: 'Card shadow',
  tabsShadow: 'Tab strip shadow',
  sidebarShadow: 'Sidebar shadow',
  pageGradientFrom: 'Page background (from)',
  pageGradientVia: 'Page background (via)',
  pageGradientTo: 'Page background (to)',
  cardGradientFrom: 'Stat / info gradient (from)',
  cardGradientVia: 'Stat / info gradient (via)',
  cardGradientTo: 'Stat / info gradient (to)',
  tabsGradientFrom: 'Tab strip gradient (from)',
  tabsGradientVia: 'Tab strip gradient (via)',
  tabsGradientTo: 'Tab strip gradient (to)',
  pageGlow: 'Backdrop glow accent',
};

export const COLOR_GROUPS: Array<{ title: string; keys: ColorHexKey[] }> = [
  {
    title: 'Backgrounds',
    keys: ['bgPrimary', 'bgTertiary', 'bgQuaternary', 'pageGradientFrom', 'pageGradientVia', 'pageGradientTo', 'pageGlow'],
  },
  {
    title: 'Surfaces',
    keys: [
      'bgSecondary',
      'panelBg',
      'cardGradientFrom',
      'cardGradientVia',
      'cardGradientTo',
    ],
  },
  { title: 'Text', keys: ['textPrimary', 'textSecondary', 'textTertiary'] },
  { title: 'Borders', keys: ['borderPrimary', 'borderSecondary'] },
  { title: 'Accents', keys: ['accentPrimary', 'accentHover'] },
  { title: 'Header', keys: ['headerBg', 'headerText', 'headerBorder', 'headerShadow'] },
  { title: 'Elevation', keys: ['panelShadow', 'cardShadow', 'tabsShadow', 'sidebarShadow'] },
  { title: 'Layout', keys: ['sidebarBg', 'sidebarBorder'] },
  { title: 'Tab Strip Gradient', keys: ['tabsGradientFrom', 'tabsGradientVia', 'tabsGradientTo'] },
];

export const LIGHT_PRESETS: Array<{ name: string; accent: string; colors: PartialColorTokens }> = [
  {
    name: 'Default',
    accent: DEFAULT_LIGHT_COLORS.accentPrimary,
    colors: DEFAULT_LIGHT_COLORS,
  },
  {
    name: 'Warm',
    accent: '#fef3dc',
    colors: {
      bgPrimary: '#fffbf5',
      bgSecondary: '#fef8ee',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#fde9be',
      textPrimary: '#1c1009',
      textSecondary: '#78461d',
      textTertiary: '#9a6b3c',
      borderPrimary: '#f5d9a0',
      borderSecondary: '#e8bc6a',
      accentPrimary: '#f59e0b',
      accentHover: '#d97706',
      headerBg: '#fffbf537',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#f5d9a04c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#fffbf53e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#f5d9a020',
      sidebarBg: '#fffbf580',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#fef3dc',
      pageGradientTo: '#ffffff',
      pageGlow: '#f59e0b73',
      surfaceRadius: 24,
      statCardAccentTop: 0,
      statCardAccentLeft: 0,
      panelShadow: '#f59e0b20',
      panelShadowBlur: 20,
      panelShadowSpread: -10,
      cardShadow: '#f59e0b30',
      cardShadowBlur: 24,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Ocean',
    accent: '#e0f2fe',
    colors: {
      bgPrimary: '#f0f9ff',
      bgSecondary: '#e0f2fe',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#7dd3fc',
      textPrimary: '#0c2d48',
      textSecondary: '#0369a1',
      textTertiary: '#0284c7',
      borderPrimary: '#bae6fd',
      borderSecondary: '#7dd3fc',
      accentPrimary: '#0ea5e9',
      accentHover: '#0284c7',
      headerBg: '#f0f9ff37',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#bae6fd4c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#f0f9ff3e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#bae6fd20',
      sidebarBg: '#f0f9ff80',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#e0f2fe',
      pageGradientTo: '#ffffff',
      pageGlow: '#0ea5e973',
      surfaceRadius: 12,
      statCardAccentTop: 4,
      statCardAccentLeft: 0,
      panelShadow: '#0ea5e91a',
      panelShadowBlur: 16,
      panelShadowSpread: -8,
      cardShadow: '#0ea5e926',
      cardShadowBlur: 20,
      cardShadowSpread: -8,
      glowOpacity: 1,
    },
  },
  {
    name: 'Lavender',
    accent: '#f3e8ff',
    colors: {
      bgPrimary: '#faf5ff',
      bgSecondary: '#f3e8ff',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#d8b4fe',
      textPrimary: '#2e1065',
      textSecondary: '#7e22ce',
      textTertiary: '#9333ea',
      borderPrimary: '#e9d5ff',
      borderSecondary: '#d8b4fe',
      accentPrimary: '#a855f7',
      accentHover: '#9333ea',
      headerBg: '#faf5ff37',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#e9d5ff4c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#faf5ff3e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#e9d5ff20',
      sidebarBg: '#faf5ff80',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#f3e8ff',
      pageGradientTo: '#ffffff',
      pageGlow: '#a855f773',
      surfaceRadius: 20,
      statCardAccentTop: 0,
      statCardAccentLeft: 4,
      panelShadow: '#a855f71a',
      panelShadowBlur: 18,
      panelShadowSpread: -8,
      cardShadow: '#a855f726',
      cardShadowBlur: 24,
      cardShadowSpread: -8,
      glowOpacity: 1,
    },
  },
  {
    name: 'Sage',
    accent: '#dcfce7',
    colors: {
      bgPrimary: '#f0fdf4',
      bgSecondary: '#dcfce7',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#86efac',
      textPrimary: '#052e16',
      textSecondary: '#15803d',
      textTertiary: '#16a34a',
      borderPrimary: '#bbf7d0',
      borderSecondary: '#86efac',
      accentPrimary: '#22c55e',
      accentHover: '#16a34a',
      headerBg: '#f0fdf437',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#bbf7d04c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#f0fdf43e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#bbf7d020',
      sidebarBg: '#f0fdf480',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#dcfce7',
      pageGradientTo: '#ffffff',
      pageGlow: '#22c55e73',
      surfaceRadius: 18,
      statCardAccentTop: 4,
      statCardAccentLeft: 4,
      panelShadow: '#22c55e14',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#22c55e20',
      cardShadowBlur: 20,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Sunset',
    accent: '#fff1f2',
    colors: {
      bgPrimary: '#fff7f7',
      bgSecondary: '#fff1f2',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#fecdd3',
      textPrimary: '#1f0b0f',
      textSecondary: '#7f1d1d',
      textTertiary: '#9f1239',
      borderPrimary: '#fecdd3',
      borderSecondary: '#fda4af',
      accentPrimary: '#fb7185',
      accentHover: '#e11d48',
      headerBg: '#fff7f737',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#fecdd34c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#fff7f73e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#fecdd320',
      sidebarBg: '#fff7f780',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#ffe4e6',
      pageGradientTo: '#ffffff',
      pageGlow: '#fb718573',
      surfaceRadius: 8,
      statCardAccentTop: 2,
      statCardAccentLeft: 2,
      panelShadow: '#fb718520',
      panelShadowBlur: 24,
      panelShadowSpread: -10,
      cardShadow: '#fb718530',
      cardShadowBlur: 30,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Citrine',
    accent: '#fffbeb',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#fffbeb',
      panelBg: DEFAULT_LIGHT_COLORS.panelBg,
      heroBg: DEFAULT_LIGHT_COLORS.heroBg,
      bgTertiary: DEFAULT_LIGHT_COLORS.bgTertiary,
      bgQuaternary: '#fde68a',
      textPrimary: '#1f1500',
      textSecondary: '#78350f',
      textTertiary: '#92400e',
      borderPrimary: '#fde68a',
      borderSecondary: '#fbbf24',
      accentPrimary: '#f59e0b',
      accentHover: '#b45309',
      headerBg: '#ffffff37',
      headerOpacity: 1,
      headerBlur: 20,
      headerBorder: '#fde68a4c',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#ffffff3e',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#fde68a20',
      sidebarBg: '#ffffff80',
      sidebarBorder: '#ececec6c',
      sidebarOpacity: 1,
      headerShadow: '#00000062',
      headerShadowBlur: 30,
      headerShadowSpread: -27,
      stickyHeaderShadow: '#9e9c9cef',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -23,
      pageGradientFrom: '#ffffff',
      pageGradientVia: '#fef3c7',
      pageGradientTo: '#ffffff',
      pageGlow: '#f59e0b73',
      surfaceRadius: 10,
      statCardAccentTop: 0,
      statCardAccentLeft: 6,
      panelShadow: '#f59e0b1a',
      panelShadowBlur: 14,
      panelShadowSpread: -6,
      cardShadow: '#f59e0b26',
      cardShadowBlur: 18,
      cardShadowSpread: -6,
      glowOpacity: 1,
    },
  },
  {
    name: 'Material',
    accent: '#6750a4',
    colors: {
      bgPrimary: '#fffbfe',
      bgSecondary: '#f7f2fa',
      panelBg: '#fffbfe',
      heroBg: '#f7f2fa',
      bgTertiary: '#ece6f0',
      bgQuaternary: '#cac4d0',
      textPrimary: '#1d1b20',
      textSecondary: '#49454f',
      textTertiary: '#79747e',
      borderPrimary: '#e7e0ec',
      borderSecondary: '#cac4d0',
      accentPrimary: '#6750a4',
      accentHover: '#4f378b',
      headerBg: '#fffbfef2',
      headerOpacity: 1,
      headerText: '#1d1b20',
      headerBlur: 0,
      headerBorder: '#e7e0ec',
      headerBorderOpacity: 1,
      headerBorderWidth: 0,
      headerMenuFontWeight: 500,
      fontFamily: 'material',
      stickyHeaderBg: '#fffbfef2',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#1d1b20',
      stickyHeaderBorder: '#e7e0ec',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 0,
      sidebarBg: '#f7f2faee',
      sidebarBorder: '#e7e0ec',
      sidebarOpacity: 1,
      headerShadow: '#1d1b200f',
      headerShadowBlur: 10,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      panelShadow: '#1d1b200d',
      panelShadowBlur: 12,
      panelShadowSpread: -4,
      cardShadow: '#1d1b201a',
      cardShadowBlur: 16,
      cardShadowSpread: -4,
      tabsShadow: '#1d1b200d',
      tabsShadowBlur: 12,
      tabsShadowSpread: -4,
      sidebarShadow: '#1d1b2010',
      sidebarShadowBlur: 10,
      sidebarShadowSpread: -12,
      stickyHeaderShadow: '#1d1b200d',
      stickyHeaderShadowBlur: 10,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#fffbfe',
      pageGradientVia: '#fcf8fd',
      pageGradientTo: '#fffbfe',
      heroGradientFrom: '#f7f2fa',
      heroGradientVia: '#f8f3fa',
      heroGradientTo: '#f7f2fa',
      cardGradientFrom: '#fffbfe',
      cardGradientVia: '#f7f2fa',
      cardGradientTo: '#fffbfe',
      tabsGradientFrom: '#fffbfe',
      tabsGradientVia: '#faf6fc',
      tabsGradientTo: '#fffbfe',
      pageGlow: '#efe7f8',
      glowOpacity: 1,
    },
  },
  {
    name: 'Fluent',
    accent: '#0f6cbd',
    colors: {
      bgPrimary: '#f3f2f1',
      bgSecondary: '#ffffff',
      panelBg: '#ffffff',
      heroBg: '#faf9f8',
      bgTertiary: '#edebe9',
      bgQuaternary: '#e1dfdd',
      textPrimary: '#201f1e',
      textSecondary: '#605e5c',
      textTertiary: '#8a8886',
      borderPrimary: '#e1dfdd',
      borderSecondary: '#c8c6c4',
      accentPrimary: '#0f6cbd',
      accentHover: '#115ea3',
      headerBg: '#ffffffd9',
      headerOpacity: 1,
      headerText: '#201f1e',
      headerBlur: 20,
      headerBorder: '#edebe9cc',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 600,
      fontFamily: 'fluent',
      stickyHeaderBg: '#ffffffe0',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 24,
      stickyHeaderText: '#201f1e',
      stickyHeaderBorder: '#edebe9cc',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f3f2f1d9',
      sidebarBorder: '#e1dfddcc',
      sidebarOpacity: 1,
      headerShadow: '#00000012',
      headerShadowBlur: 20,
      headerShadowSpread: -20,
      surfaceRadius: 6,
      statCardAccentTop: 4,
      panelShadow: '#00000010',
      panelShadowBlur: 16,
      panelShadowSpread: -12,
      cardShadow: '#00000016',
      cardShadowBlur: 16,
      cardShadowSpread: -12,
      tabsShadow: '#00000010',
      tabsShadowBlur: 16,
      tabsShadowSpread: -12,
      sidebarShadow: '#00000014',
      sidebarShadowBlur: 22,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000012',
      stickyHeaderShadowBlur: 20,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#f7f8fa',
      pageGradientVia: '#f3f6f9',
      pageGradientTo: '#f3f2f1',
      heroGradientFrom: '#ffffff',
      heroGradientVia: '#f8fafc',
      heroGradientTo: '#faf9f8',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fbfdff',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#faf9f8',
      tabsGradientVia: '#f5f7fa',
      tabsGradientTo: '#faf9f8',
      pageGlow: '#d9ebfb',
      glowOpacity: 1,
    },
  },
  {
    name: 'Apple HIG',
    accent: '#0071e3',
    colors: {
      bgPrimary: '#f5f5f7',
      bgSecondary: '#ffffff',
      panelBg: '#ffffff',
      heroBg: '#fbfbfd',
      bgTertiary: '#f0f0f2',
      bgQuaternary: '#d2d2d7',
      textPrimary: '#1d1d1f',
      textSecondary: '#424245',
      textTertiary: '#6e6e73',
      borderPrimary: '#00000010',
      borderSecondary: '#00000018',
      accentPrimary: '#0071e3',
      accentHover: '#005bb5',
      headerBg: '#fbfbfdc7',
      headerOpacity: 1,
      headerText: '#1d1d1f',
      headerBlur: 30,
      headerBorder: '#ffffff66',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'apple',
      stickyHeaderBg: '#fbfbfdd6',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 34,
      stickyHeaderText: '#1d1d1f',
      stickyHeaderBorder: '#ffffff5c',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#f5f5f7bd',
      sidebarBorder: '#ffffff55',
      sidebarOpacity: 1,
      headerShadow: '#00000012',
      headerShadowBlur: 18,
      headerShadowSpread: -20,
      surfaceRadius: 20,
      statCardAccentTop: 0,
      panelShadow: '#0000000e',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#00000014',
      cardShadowBlur: 28,
      cardShadowSpread: -8,
      tabsShadow: '#0000000e',
      tabsShadowBlur: 16,
      tabsShadowSpread: -10,
      sidebarShadow: '#00000010',
      sidebarShadowBlur: 18,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000012',
      stickyHeaderShadowBlur: 18,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#f7f7f9',
      pageGradientVia: '#f5f5f7',
      pageGradientTo: '#f2f2f4',
      heroGradientFrom: '#ffffff',
      heroGradientVia: '#fbfbfd',
      heroGradientTo: '#ffffff',
      cardGradientFrom: '#ffffff',
      cardGradientVia: '#fbfbfd',
      cardGradientTo: '#ffffff',
      tabsGradientFrom: '#f7f7f9',
      tabsGradientVia: '#f5f5f7',
      tabsGradientTo: '#f7f7f9',
      pageGlow: '#ffffff',
      glowOpacity: 1,
    },
  },
];

export const DARK_PRESETS: Array<{ name: string; accent: string; colors: PartialColorTokens }> = [
  {
    name: 'Default',
    accent: DEFAULT_DARK_COLORS.accentPrimary,
    colors: DEFAULT_DARK_COLORS,
  },
  {
    name: 'Midnight',
    accent: '#0a1628',
    colors: {
      bgPrimary: '#020616',
      bgSecondary: '#0a1628',
      panelBg: DEFAULT_DARK_COLORS.panelBg,
      heroBg: DEFAULT_DARK_COLORS.heroBg,
      bgTertiary: DEFAULT_DARK_COLORS.bgTertiary,
      bgQuaternary: '#1e3a5f',
      textPrimary: '#e0f2fe',
      textSecondary: '#7dd3fc',
      textTertiary: '#38bdf8',
      borderPrimary: '#1e3a5f7f',
      borderSecondary: '#2e4e7ec3',
      accentPrimary: '#38bdf8',
      accentHover: '#0ea5e9',
      headerBg: '#0206163e',
      headerOpacity: 1,
      headerBorder: '#1e3a5f79',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#02061635',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#1e3a5f00',
      sidebarBg: '#0a16285d',
      sidebarBorder: '#1e3a5f00',
      sidebarOpacity: 1,
      headerShadow: '#8e8e8e61',
      headerShadowBlur: 30,
      headerShadowSpread: -23,
      stickyHeaderShadow: '#6f6f6f7d',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -19,
      pageGradientFrom: '#020616',
      pageGradientVia: '#0a1628',
      pageGradientTo: '#020616',
      pageGlow: '#38bdf8c7',
      surfaceRadius: 14,
      statCardAccentTop: 0,
      statCardAccentLeft: 4,
      panelShadow: '#38bdf814',
      panelShadowBlur: 20,
      panelShadowSpread: -10,
      cardShadow: '#38bdf820',
      cardShadowBlur: 24,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Amethyst',
    accent: '#1a0f2e',
    colors: {
      bgPrimary: '#0f0a1f',
      bgSecondary: '#1a0f2e',
      panelBg: DEFAULT_DARK_COLORS.panelBg,
      heroBg: DEFAULT_DARK_COLORS.heroBg,
      bgTertiary: DEFAULT_DARK_COLORS.bgTertiary,
      bgQuaternary: '#3d2468',
      textPrimary: '#ede9fe',
      textSecondary: '#c084fc',
      textTertiary: '#a855f7',
      borderPrimary: '#3d24687f',
      borderSecondary: '#5b3a8ac3',
      accentPrimary: '#c084fc',
      accentHover: '#a855f7',
      headerBg: '#0f0a1f3e',
      headerOpacity: 1,
      headerBorder: '#3d246879',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#0f0a1f35',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#3d246800',
      sidebarBg: '#1a0f2e5d',
      sidebarBorder: '#3d246800',
      sidebarOpacity: 1,
      headerShadow: '#8e8e8e61',
      headerShadowBlur: 30,
      headerShadowSpread: -23,
      stickyHeaderShadow: '#6f6f6f7d',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -19,
      pageGradientFrom: '#0f0a1f',
      pageGradientVia: '#1a0f2e',
      pageGradientTo: '#0a0a0a',
      pageGlow: '#c084fcc7',
      surfaceRadius: 20,
      statCardAccentTop: 4,
      statCardAccentLeft: 0,
      panelShadow: '#c084fc1a',
      panelShadowBlur: 18,
      panelShadowSpread: -8,
      cardShadow: '#c084fc26',
      cardShadowBlur: 22,
      cardShadowSpread: -8,
      glowOpacity: 1,
    },
  },
  {
    name: 'Obsidian',
    accent: '#0a0a0a',
    colors: {
      bgPrimary: '#000000',
      bgSecondary: '#0a0a0a',
      panelBg: DEFAULT_DARK_COLORS.panelBg,
      heroBg: DEFAULT_DARK_COLORS.heroBg,
      bgTertiary: DEFAULT_DARK_COLORS.bgTertiary,
      bgQuaternary: '#1f1f1f',
      textPrimary: '#ffffff',
      textSecondary: '#a0a0a0',
      textTertiary: '#6b6b6b',
      borderPrimary: '#1f1f1f7f',
      borderSecondary: '#2d2d2dc3',
      accentPrimary: '#6366f1',
      accentHover: '#4f46e5',
      headerBg: '#0000003e',
      headerOpacity: 1,
      headerBorder: '#1f1f1f79',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#00000035',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#1f1f1f00',
      sidebarBg: '#0a0a0a5d',
      sidebarBorder: '#1f1f1f00',
      sidebarOpacity: 1,
      headerShadow: '#8e8e8e61',
      headerShadowBlur: 30,
      headerShadowSpread: -23,
      stickyHeaderShadow: '#6f6f6f7d',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -19,
      pageGradientFrom: '#000000',
      pageGradientVia: '#0a0a0a',
      pageGradientTo: '#000000',
      pageGlow: '#6366f1c7',
      surfaceRadius: 0,
      statCardAccentTop: 0,
      statCardAccentLeft: 6,
      panelShadow: '#00000000',
      panelShadowBlur: 0,
      panelShadowSpread: 0,
      cardShadow: '#ffffff0a',
      cardShadowBlur: 10,
      cardShadowSpread: -8,
      glowOpacity: 1,
    },
  },
  {
    name: 'Forest',
    accent: '#0d261e',
    colors: {
      bgPrimary: '#071612',
      bgSecondary: '#0d261e',
      panelBg: DEFAULT_DARK_COLORS.panelBg,
      heroBg: DEFAULT_DARK_COLORS.heroBg,
      bgTertiary: DEFAULT_DARK_COLORS.bgTertiary,
      bgQuaternary: '#1c4d3a',
      textPrimary: '#d1fae5',
      textSecondary: '#6ee7b7',
      textTertiary: '#34d399',
      borderPrimary: '#1c4d3a7f',
      borderSecondary: '#276048c3',
      accentPrimary: '#34d399',
      accentHover: '#10b981',
      headerBg: '#0716123e',
      headerOpacity: 1,
      headerBorder: '#1c4d3a79',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#07161235',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#1c4d3a00',
      sidebarBg: '#0d261e5d',
      sidebarBorder: '#1c4d3a00',
      sidebarOpacity: 1,
      headerShadow: '#8e8e8e61',
      headerShadowBlur: 30,
      headerShadowSpread: -23,
      stickyHeaderShadow: '#6f6f6f7d',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -19,
      pageGradientFrom: '#071612',
      pageGradientVia: '#0d261e',
      pageGradientTo: '#071612',
      pageGlow: '#34d399c7',
      surfaceRadius: 18,
      statCardAccentTop: 4,
      statCardAccentLeft: 4,
      panelShadow: '#10b98114',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#10b9811e',
      cardShadowBlur: 20,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Neon Rose',
    accent: '#0b0b14',
    colors: {
      bgPrimary: '#070712',
      bgSecondary: '#0b0b14',
      panelBg: DEFAULT_DARK_COLORS.panelBg,
      heroBg: DEFAULT_DARK_COLORS.heroBg,
      bgTertiary: DEFAULT_DARK_COLORS.bgTertiary,
      bgQuaternary: '#1f1f3a',
      textPrimary: '#f5f5f5',
      textSecondary: '#fbcfe8',
      textTertiary: '#fda4af',
      borderPrimary: '#1f1f3a7f',
      borderSecondary: '#2b2b55c3',
      accentPrimary: '#fb7185',
      accentHover: '#e11d48',
      headerBg: '#0707123e',
      headerOpacity: 1,
      headerBorder: '#1f1f3a79',
      headerMenuFontWeight: 600,
      stickyHeaderBg: '#07071235',
      stickyHeaderBlur: 15,
      stickyHeaderBorder: '#1f1f3a00',
      sidebarBg: '#0b0b145d',
      sidebarBorder: '#1f1f3a00',
      sidebarOpacity: 1,
      headerShadow: '#8e8e8e61',
      headerShadowBlur: 30,
      headerShadowSpread: -23,
      stickyHeaderShadow: '#6f6f6f7d',
      stickyHeaderShadowBlur: 30,
      stickyHeaderShadowSpread: -19,
      pageGradientFrom: '#070712',
      pageGradientVia: '#131326',
      pageGradientTo: '#000000',
      pageGlow: '#fb7185c7',
      surfaceRadius: 8,
      statCardAccentTop: 2,
      statCardAccentLeft: 2,
      panelShadow: '#fb718520',
      panelShadowBlur: 24,
      panelShadowSpread: -10,
      cardShadow: '#fb718538',
      cardShadowBlur: 32,
      cardShadowSpread: -10,
      glowOpacity: 1,
    },
  },
  {
    name: 'Material',
    accent: '#d0bcff',
    colors: {
      bgPrimary: '#141218',
      bgSecondary: '#1d1b20',
      panelBg: '#211f26',
      heroBg: '#1d1b20',
      bgTertiary: '#2b2930',
      bgQuaternary: '#49454f',
      textPrimary: '#e6e1e5',
      textSecondary: '#cac4d0',
      textTertiary: '#938f99',
      borderPrimary: '#49454f80',
      borderSecondary: '#938f99',
      accentPrimary: '#d0bcff',
      accentHover: '#b69df8',
      headerBg: '#1d1b20f2',
      headerOpacity: 1,
      headerText: '#e6e1e5',
      headerBlur: 0,
      headerBorder: '#49454f80',
      headerBorderOpacity: 1,
      headerBorderWidth: 0,
      headerMenuFontWeight: 500,
      fontFamily: 'material',
      stickyHeaderBg: '#1d1b20f5',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 0,
      stickyHeaderText: '#e6e1e5',
      stickyHeaderBorder: '#49454f80',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 0,
      sidebarBg: '#1d1b20eb',
      sidebarBorder: '#49454f80',
      sidebarOpacity: 1,
      headerShadow: '#00000024',
      headerShadowBlur: 12,
      headerShadowSpread: -10,
      surfaceRadius: 12,
      statCardAccentTop: 0,
      panelShadow: '#0000002a',
      panelShadowBlur: 12,
      panelShadowSpread: -4,
      cardShadow: '#00000035',
      cardShadowBlur: 16,
      cardShadowSpread: -4,
      tabsShadow: '#0000002a',
      tabsShadowBlur: 12,
      tabsShadowSpread: -4,
      sidebarShadow: '#00000028',
      sidebarShadowBlur: 12,
      sidebarShadowSpread: -14,
      stickyHeaderShadow: '#00000026',
      stickyHeaderShadowBlur: 12,
      stickyHeaderShadowSpread: -10,
      pageGradientFrom: '#141218',
      pageGradientVia: '#17141c',
      pageGradientTo: '#141218',
      heroGradientFrom: '#1d1b20',
      heroGradientVia: '#211f26',
      heroGradientTo: '#1d1b20',
      cardGradientFrom: '#211f26',
      cardGradientVia: '#2b2930',
      cardGradientTo: '#211f26',
      tabsGradientFrom: '#1d1b20',
      tabsGradientVia: '#221f27',
      tabsGradientTo: '#1d1b20',
      pageGlow: '#141218',
      glowOpacity: 1,
    },
  },
  {
    name: 'Fluent',
    accent: '#60cdff',
    colors: {
      bgPrimary: '#1b1a19',
      bgSecondary: '#201f1e',
      panelBg: '#252423',
      heroBg: '#242322',
      bgTertiary: '#323130',
      bgQuaternary: '#484644',
      textPrimary: '#f3f2f1',
      textSecondary: '#c8c6c4',
      textTertiary: '#a19f9d',
      borderPrimary: '#3b3a39',
      borderSecondary: '#605e5c',
      accentPrimary: '#60cdff',
      accentHover: '#4cc2ff',
      headerBg: '#201f1ecc',
      headerOpacity: 1,
      headerText: '#f3f2f1',
      headerBlur: 20,
      headerBorder: '#3b3a39c8',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 600,
      fontFamily: 'fluent',
      stickyHeaderBg: '#201f1ed9',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 24,
      stickyHeaderText: '#f3f2f1',
      stickyHeaderBorder: '#3b3a39d4',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#252423cc',
      sidebarBorder: '#3b3a39cc',
      sidebarOpacity: 1,
      headerShadow: '#00000028',
      headerShadowBlur: 20,
      headerShadowSpread: -20,
      surfaceRadius: 6,
      statCardAccentTop: 4,
      panelShadow: '#00000026',
      panelShadowBlur: 18,
      panelShadowSpread: -12,
      cardShadow: '#00000035',
      cardShadowBlur: 16,
      cardShadowSpread: -12,
      tabsShadow: '#00000024',
      tabsShadowBlur: 18,
      tabsShadowSpread: -12,
      sidebarShadow: '#00000030',
      sidebarShadowBlur: 22,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#0000002c',
      stickyHeaderShadowBlur: 20,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#1b1a19',
      pageGradientVia: '#1f252c',
      pageGradientTo: '#1b1a19',
      heroGradientFrom: '#252423',
      heroGradientVia: '#242b34',
      heroGradientTo: '#252423',
      cardGradientFrom: '#252423',
      cardGradientVia: '#232a33',
      cardGradientTo: '#252423',
      tabsGradientFrom: '#201f1e',
      tabsGradientVia: '#20262f',
      tabsGradientTo: '#201f1e',
      pageGlow: '#0f6cbd33',
      glowOpacity: 1,
    },
  },
  {
    name: 'Apple HIG',
    accent: '#0a84ff',
    colors: {
      bgPrimary: '#0b0b0f',
      bgSecondary: '#1c1c1e',
      panelBg: '#1c1c1e',
      heroBg: '#161618',
      bgTertiary: '#2c2c2e',
      bgQuaternary: '#3a3a3c',
      textPrimary: '#f5f5f7',
      textSecondary: '#d1d1d6',
      textTertiary: '#8e8e93',
      borderPrimary: '#ffffff10',
      borderSecondary: '#ffffff18',
      accentPrimary: '#0a84ff',
      accentHover: '#409cff',
      headerBg: '#1c1c1eb8',
      headerOpacity: 1,
      headerText: '#f5f5f7',
      headerBlur: 30,
      headerBorder: '#ffffff12',
      headerBorderOpacity: 1,
      headerBorderWidth: 1,
      headerMenuFontWeight: 500,
      fontFamily: 'apple',
      stickyHeaderBg: '#1c1c1ecc',
      stickyHeaderOpacity: 1,
      stickyHeaderBlur: 34,
      stickyHeaderText: '#f5f5f7',
      stickyHeaderBorder: '#ffffff10',
      stickyHeaderBorderOpacity: 1,
      stickyHeaderBorderWidth: 1,
      sidebarBg: '#161618c7',
      sidebarBorder: '#ffffff10',
      sidebarOpacity: 1,
      headerShadow: '#00000024',
      headerShadowBlur: 18,
      headerShadowSpread: -20,
      surfaceRadius: 20,
      statCardAccentTop: 0,
      panelShadow: '#00000025',
      panelShadowBlur: 16,
      panelShadowSpread: -10,
      cardShadow: '#00000035',
      cardShadowBlur: 28,
      cardShadowSpread: -8,
      tabsShadow: '#00000025',
      tabsShadowBlur: 14,
      tabsShadowSpread: -10,
      sidebarShadow: '#00000022',
      sidebarShadowBlur: 18,
      sidebarShadowSpread: -20,
      stickyHeaderShadow: '#00000028',
      stickyHeaderShadowBlur: 18,
      stickyHeaderShadowSpread: -20,
      pageGradientFrom: '#0b0b0f',
      pageGradientVia: '#111216',
      pageGradientTo: '#0b0b0f',
      heroGradientFrom: '#161618',
      heroGradientVia: '#1c1c20',
      heroGradientTo: '#161618',
      cardGradientFrom: '#1f1f22',
      cardGradientVia: '#1c1c1f',
      cardGradientTo: '#1f1f22',
      tabsGradientFrom: '#111216',
      tabsGradientVia: '#15161a',
      tabsGradientTo: '#111216',
      pageGlow: '#0a84ff18',
      glowOpacity: 1,
    },
  },
];
